import type { Difficulty, StageId } from "./types";
import { STAGE_RUNTIME_MANIFEST } from "./stage-runtime";
import type { DebugRosterSourceId } from "./debug-roster-profiles";

export interface DebugScenarioDefinition {
  id: string;
  stageId: StageId;
  title: string;
  phase: string;
  description: string;
  fixture?: boolean;
}

export function debugStageLabel(stageId: StageId): string {
  const stage = STAGE_RUNTIME_MANIFEST[stageId];
  return `第 ${stage.ordinal} 關 · ${stage.label}`;
}

export const DEBUG_SCENARIOS = [
  {
    id: "stage-00-prebattle",
    stageId: "stage-00",
    title: "關前劇情",
    phase: "SAY/0000",
    description: "從本關最初狀態開始，保留劇情、腳本移動和開戰對白。",
  },
  {
    id: "stage-00-player",
    stageId: "stage-00",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過關前演出，直接進入完整初始戰場的玩家階段。",
  },
  {
    id: "stage-00-near-victory",
    stageId: "stage-00",
    title: "一擊勝利",
    phase: "Victory setup",
    description: "只保留 1 點生命的最後敵人，攻擊一次即可驗證勝利流程。",
    fixture: true,
  },
  {
    id: "stage-00-cleared",
    stageId: "stage-00",
    title: "直接通關",
    phase: "Route to stage 1",
    description: "視為第 0 關已經完成，直接進入第 1 關關前劇情。",
    fixture: true,
  },
  {
    id: "stage-01-prebattle",
    stageId: "stage-01",
    title: "關前劇情",
    phase: "SAY/0004",
    description: "以完整戰役 roster 進入第 1 關關前劇情。",
  },
  {
    id: "stage-01-deployment",
    stageId: "stage-01",
    title: "部署",
    phase: "5/8 initial",
    description: "直接開啟正式部署介面，保留固定、可選、空位和錯誤規則。",
  },
  {
    id: "stage-01-player",
    stageId: "stage-01",
    title: "玩家回合",
    phase: "Round 1",
    description: "用六人編隊直接開戰，葛蒂拉斯已經部署。",
  },
  {
    id: "stage-01-magician",
    stageId: "stage-01",
    title: "魔術士技能靶場",
    phase: "1F / 1L / 1C",
    description: "追擊型敵兵位於冰雪最外圈，可驗證 REMAKE-036 外推到值 0，並只跳過一次敵方行動。",
    fixture: true,
  },
  {
    id: "stage-01-dispel",
    stageId: "stage-01",
    title: "冰封／破邪靶場",
    phase: "TR / REMAKE-013",
    description: "魔祭師可對相鄰冰封友軍施展破邪，驗證攻擊／治療不可選與演出後解封。",
    fixture: true,
  },
  {
    id: "stage-01-enemy-sister",
    stageId: "stage-01",
    title: "敵方修女範圍",
    phase: "Unified range 5",
    description: "敵方修女位於統一炎暴範圍 5 的邊界，結束回合即可觀察施法。",
    fixture: true,
  },
  {
    id: "stage-01-near-victory",
    stageId: "stage-01",
    title: "一擊擊敗娜米",
    phase: "Victory 999",
    description: "娜米只剩 1 點生命且位於妮雅身邊，攻擊一次進入傳令兵流程。",
    fixture: true,
  },
  {
    id: "stage-01-cleared",
    stageId: "stage-01",
    title: "直接通關",
    phase: "Route to stage 2",
    description: "視為第 1 關已經完成，直接進入第 2 關開場事件。",
    fixture: true,
  },
  {
    id: "stage-02-prebattle",
    stageId: "stage-02",
    title: "關前／開場敘事",
    phase: "SAY/0155",
    description: "由第 1 關完成 roster 建立固定戰場，保留第 1 回合開場敘事。",
  },
  {
    id: "stage-02-preparation",
    stageId: "stage-02",
    title: "固定編隊準備",
    phase: "Fixed 9 vs 5",
    description: "顯示完整固定陣容與自動友軍標記；本關沒有交互部署。",
  },
  {
    id: "stage-02-player",
    stageId: "stage-02",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場敘事，直接驗證三名手動角色與六名自動友軍。",
  },
  {
    id: "stage-02-near-victory",
    stageId: "stage-02",
    title: "一擊擊敗萊莉",
    phase: "Victory 999",
    description: "萊莉只剩 1 點生命且位於妮雅身邊，攻擊一次進入 SAY/0175。",
    fixture: true,
  },
  {
    id: "stage-02-cleared",
    stageId: "stage-02",
    title: "完成路由",
    phase: "Route to stage 3",
    description: "視為第 2 關已完成，直接進入第 3 關開場事件。",
    fixture: true,
  },
  {
    id: "stage-03-prebattle",
    stageId: "stage-03",
    title: "關前／開場敘事",
    phase: "SAY/0012",
    description: "由第 2 關完成 roster 建立固定戰場，保留希蜜與第四軍團會合敘事。",
  },
  {
    id: "stage-03-preparation",
    stageId: "stage-03",
    title: "固定編隊準備",
    phase: "Fixed 13 vs 12",
    description: "顯示完整固定陣容、黛西領隊與跟隨者；本關沒有交互部署。",
  },
  {
    id: "stage-03-player",
    stageId: "stage-03",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場敘事，直接驗證希蜜軍團與第四軍團的手動／自動分工。",
  },
  {
    id: "stage-03-himi-defeat",
    stageId: "stage-03",
    title: "希蜜戰敗",
    phase: "Defeat slot 1",
    description: "直接移除救援主將希蜜，驗證本關第一個特殊保護目標與戰敗回饋。",
    fixture: true,
  },
  {
    id: "stage-03-daisy-defeat",
    stageId: "stage-03",
    title: "黛西戰敗",
    phase: "Defeat slot 3",
    description: "直接移除第四軍團領隊黛西，驗證自動友軍同樣是本關特殊保護目標。",
    fixture: true,
  },
  {
    id: "stage-03-near-victory",
    stageId: "stage-03",
    title: "一擊擊敗梅蒂",
    phase: "Victory 999",
    description: "梅蒂只剩 1 點生命且位於可控主將身邊，攻擊一次進入 SAY/0013。",
    fixture: true,
  },
  {
    id: "stage-03-cleared",
    stageId: "stage-03",
    title: "完成路由",
    phase: "Route to stage 4",
    description: "視為第 3 關已完成，直接進入第 4 關關前劇情。",
    fixture: true,
  },
  {
    id: "stage-04-prebattle",
    stageId: "stage-04",
    title: "關前劇情",
    phase: "SAY/0007",
    description: "從本關最初狀態開始，保留騎士團堡外的完整關前劇情。",
  },
  {
    id: "stage-04-deployment",
    stageId: "stage-04",
    title: "結界部署",
    phase: "2/8 initial",
    description: "直接開啟正式部署介面，標示首輪安全區與兩個危險空位。",
  },
  {
    id: "stage-04-player",
    stageId: "stage-04",
    title: "玩家回合",
    phase: "Round 1",
    description: "以八人編隊直接開戰，葛蒂拉斯由獨立友軍 AI 控制。",
  },
  {
    id: "stage-04-first-pulse",
    stageId: "stage-04",
    title: "首輪力場脈衝",
    phase: "Behavior 12 / MAGIC 26",
    description: "八人全編隊保留兩名結界外角色，用於驗證移動後必定發動的生命減半與原版動畫。",
    fixture: true,
  },
  {
    id: "stage-04-near-victory",
    stageId: "stage-04",
    title: "一步抵達出口",
    phase: "Victory 999",
    description: "葛蒂拉斯距出口一次獨立行動，結束玩家回合即可進入 SAY/0174。",
    fixture: true,
  },
  {
    id: "stage-04-cleared",
    stageId: "stage-04",
    title: "完成路由",
    phase: "Route to stage 5",
    description: "視為第 4 關已完成，直接進入第 5 關內殿部署。",
    fixture: true,
  },
  {
    id: "stage-05-deployment",
    stageId: "stage-05",
    title: "內殿部署",
    phase: "1/6 initial",
    description: "直接開啟正式部署；妮雅固定，七名候選最多選五人。",
  },
  {
    id: "stage-05-player",
    stageId: "stage-05",
    title: "玩家回合",
    phase: "Round 1",
    description: "六人編隊直接進入玩家階段，保留十四名敵軍與雙首領目標。",
  },
  {
    id: "stage-05-near-tintachi",
    stageId: "stage-05",
    title: "一擊擊敗汀塔琪",
    phase: "Victory slot 25",
    description: "汀塔琪只剩 1 點生命且位於妮雅身邊；萊茵仍在場。",
    fixture: true,
  },
  {
    id: "stage-05-near-rhein",
    stageId: "stage-05",
    title: "一擊擊敗萊茵",
    phase: "Victory slot 26",
    description: "萊茵只剩 1 點生命且位於妮雅身邊；汀塔琪仍在場。",
    fixture: true,
  },
  {
    id: "stage-05-near-defeat",
    stageId: "stage-05",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-05-victory-ready",
    stageId: "stage-05",
    title: "勝利準備",
    phase: "SAY/0010",
    description: "汀塔琪已離場，直接驗證恢復神志劇情、勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-05-cleared",
    stageId: "stage-05",
    title: "完成路由",
    phase: "Route to scene 42",
    description: "模擬第 5 關完成檔，建立現場傳送門過場且不重播 SAY/0010。",
    fixture: true,
  },
  {
    id: "stage-42-portal-live",
    stageId: "stage-42-portal",
    title: "傳送門現場",
    phase: "Live 999 timeline",
    description: "從 B/0085 台陣開始，播放兩次移動、四段劇情、完整究級落雷與離場。",
    fixture: true,
  },
  {
    id: "stage-42-completed-route",
    stageId: "stage-42-portal",
    title: "傳送門完成路由",
    phase: "Loaded 1000",
    description: "不重播傳送門表現或棋盤修改，直接進入第 6 關部署。",
    fixture: true,
  },
  {
    id: "stage-06-deployment",
    stageId: "stage-06",
    title: "異世界部署",
    phase: "1/9 initial",
    description: "直接開啟正式部署；妮雅固定，十二名候選最多選八人。",
  },
  {
    id: "stage-06-prebattle",
    stageId: "stage-06",
    title: "關前劇情",
    phase: "SAY/0014",
    description: "以九人編隊完成部署，播放異世界森林與騎士團追擊劇情。",
  },
  {
    id: "stage-06-player",
    stageId: "stage-06",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0014、SAY/0015，以九人編隊直接迎戰西艾蕾追擊隊。",
  },
  {
    id: "stage-06-near-xielei",
    stageId: "stage-06",
    title: "一擊擊敗西艾蕾",
    phase: "Victory slot 19",
    description: "西艾蕾只剩 1 點生命且位於妮雅身邊；其餘追擊隊已離場。",
    fixture: true,
  },
  {
    id: "stage-06-near-defeat",
    stageId: "stage-06",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-06-victory-ready",
    stageId: "stage-06",
    title: "勝利準備",
    phase: "SAY/0016",
    description: "西艾蕾已離場，直接驗證撤退劇情、游騎兵台陣、領隊移動與 SAY/0115。",
    fixture: true,
  },
  {
    id: "stage-06-cleared",
    stageId: "stage-06",
    title: "完成路由",
    phase: "Route to stage 7",
    description: "視為第 6 關已完成，直接進入第 7 關營地劇情。",
    fixture: true,
  },
  {
    id: "stage-07-prebattle",
    stageId: "stage-07",
    title: "關前劇情",
    phase: "SAY/0017",
    description: "從本關最初狀態開始，保留游騎兵營地白天／夜間的雙背景劇情。",
  },
  {
    id: "stage-07-deployment",
    stageId: "stage-07",
    title: "營地守備部署",
    phase: "2/7 initial",
    description: "直接開啟正式部署；妮雅、希蜜固定，十一名候選最多選五人。",
  },
  {
    id: "stage-07-player",
    stageId: "stage-07",
    title: "玩家回合",
    phase: "Round 1",
    description: "七人編隊直接進入玩家階段，保留十一名敵軍與萊莉首領目標。",
  },
  {
    id: "stage-07-near-laili",
    stageId: "stage-07",
    title: "一擊擊敗萊莉",
    phase: "Victory slot 18",
    description: "萊莉只剩 1 點生命且位於妮雅身邊；其餘奇襲隊仍在場。",
    fixture: true,
  },
  {
    id: "stage-07-near-defeat",
    stageId: "stage-07",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-07-victory-ready",
    stageId: "stage-07",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "萊莉已離場，直接驗證無戰後劇情的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-07-cleared",
    stageId: "stage-07",
    title: "完成路由",
    phase: "Route to stage 8",
    description: "視為第 7 關已完成，直接進入「營地遭到偷襲」第 8 關關前劇情。",
    fixture: true,
  },
  {
    id: "stage-08-prebattle",
    stageId: "stage-08",
    title: "關前劇情",
    phase: "SAY/0021",
    description: "從本關最初狀態開始，保留 BK/7、BK/6、BK/8 三背景劇情。",
  },
  {
    id: "stage-08-opening",
    stageId: "stage-08",
    title: "開戰劇情",
    phase: "SAY/0156",
    description: "跳過關前劇情，直接查看固定戰場上的第 1 回合兩頁說明。",
  },
  {
    id: "stage-08-player",
    stageId: "stage-08",
    title: "玩家回合",
    phase: "Round 1",
    description: "八名我方單位全部由玩家操作，蘇蘭達擔任集團主將。",
  },
  {
    id: "stage-08-free-action",
    stageId: "stage-08",
    title: "自由行動",
    phase: "Free action",
    description: "發出自由行動命令，驗證八名玩家單位可主動交給共享專家 AI。",
    fixture: true,
  },
  {
    id: "stage-08-near-victory",
    stageId: "stage-08",
    title: "最後一名敵軍",
    phase: "Eliminate side 2",
    description: "其餘十名襲擊者已離場，最後一名敵軍只剩 1 點生命並位於蘇蘭達身邊。",
    fixture: true,
  },
  {
    id: "stage-08-near-defeat",
    stageId: "stage-08",
    title: "蘇蘭達近敗",
    phase: "Defeat setup",
    description: "蘇蘭達只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-08-victory-ready",
    stageId: "stage-08",
    title: "勝利對白",
    phase: "SAY/0157",
    description: "全部敵軍已離場，驗證 REMAKE-032 補播的蘇蘭達撤離對白與後續編號保存。",
    fixture: true,
  },
  {
    id: "stage-08-cleared",
    stageId: "stage-08",
    title: "完成路由",
    phase: "Route to stage 9",
    description: "視為第 8 關已完成，直接進入「找尋傳說中的飛船」第 9 關部署。",
    fixture: true,
  },
  {
    id: "stage-09-deployment",
    stageId: "stage-09",
    title: "死亡之谷部署",
    phase: "2/9 initial",
    description: "直接開啟正式部署；多莉與妮雅固定，十二名候選最多選七人。",
  },
  {
    id: "stage-09-opening",
    stageId: "stage-09",
    title: "開戰對白",
    phase: "SAY/0022",
    description: "九人編隊完成部署，直接查看多莉請求妮雅保護的五頁對白。",
  },
  {
    id: "stage-09-player",
    stageId: "stage-09",
    title: "玩家回合",
    phase: "Round 1",
    description: "九人編隊進入玩家階段；多莉依原版路線獨立引路，其餘八人由玩家控制。",
  },
  {
    id: "stage-09-near-route",
    stageId: "stage-09",
    title: "多莉一步登船",
    phase: "Behavior 12 / Victory 999",
    description: "多莉距谷頂一次獨立行動；結束玩家回合即可驗證安全終點與 SAY/0023。",
    fixture: true,
  },
  {
    id: "stage-09-near-elimination",
    stageId: "stage-09",
    title: "最後一名敵軍",
    phase: "Alternative victory",
    description: "其餘封鎖隊已離場，最後一名敵軍只剩 1 點生命並位於妮雅身邊。",
    fixture: true,
  },
  {
    id: "stage-09-near-defeat",
    stageId: "stage-09",
    title: "多莉近敗",
    phase: "Defeat setup",
    description: "多莉只剩 1 點生命，最近敵兵位於相鄰格，可驗證雙保護目標。",
    fixture: true,
  },
  {
    id: "stage-09-victory-ready",
    stageId: "stage-09",
    title: "勝利對白",
    phase: "SAY/0023",
    description: "以全滅替代條件直接觸發勝利，驗證多莉登船對白與編號保存。",
    fixture: true,
  },
  {
    id: "stage-09-cleared",
    stageId: "stage-09",
    title: "完成路由",
    phase: "Route to stage 11",
    description: "視為第 9 關已完成，直接進入「拯救蘇蘭達」固定戰場與 SAY/0024。",
    fixture: true,
  },
  {
    id: "stage-11-opening",
    stageId: "stage-11",
    title: "飛船抵達",
    phase: "SAY/0024–0026",
    description: "查看蘇蘭達整隊、妮雅放下繩梯與全軍登船的十三頁開場對白；結束後多莉才離開棋盤。",
  },
  {
    id: "stage-11-player",
    stageId: "stage-11",
    title: "玩家回合",
    phase: "Round 1",
    description: "多莉已留在飛船上，蘇蘭達與七名游騎兵全部由玩家控制。",
  },
  {
    id: "stage-11-near-route",
    stageId: "stage-11",
    title: "一步抵達登船區",
    phase: "Victory 999",
    description: "蘇蘭達距原版格號 0..279 登船區一步，可直接驗證護送勝利。",
    fixture: true,
  },
  {
    id: "stage-11-near-defeat",
    stageId: "stage-11",
    title: "蘇蘭達近敗",
    phase: "Defeat setup",
    description: "蘇蘭達只剩 1 點生命，初始飛馬追擊兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-11-victory-ready",
    stageId: "stage-11",
    title: "登船完成對白",
    phase: "SAY/0027",
    description: "蘇蘭達已進入登船區，直接驗證全員上船、出發對白與編號保存。",
    fixture: true,
  },
  {
    id: "stage-11-cleared",
    stageId: "stage-11",
    title: "完成路由",
    phase: "Route to stage 10",
    description: "視為拯救蘇蘭達已完成，直接進入「飛船上遭遇敵人」關前劇情。",
    fixture: true,
  },
  {
    id: "stage-10-prebattle",
    stageId: "stage-10",
    title: "關前劇情",
    phase: "SAY/0028",
    description: "查看飞船上讨论龙塔去向与追兵迫近的 15 页 BK/10 剧情。",
  },
  {
    id: "stage-10-deployment",
    stageId: "stage-10",
    title: "飛船甲板部署",
    phase: "1/13 initial",
    description: "直接開啟正式部署；妮雅固定，十九名候選最多選十二人。",
  },
  {
    id: "stage-10-player",
    stageId: "stage-10",
    title: "玩家回合",
    phase: "Round 1",
    description: "十三人完整編隊進入玩家階段，對抗五名飛馬／半龍追兵。",
  },
  {
    id: "stage-10-near-victory",
    stageId: "stage-10",
    title: "最後一名追兵",
    phase: "Eliminate side 2",
    description: "其餘四名追兵已離場，最後一名敵軍只剩 1 點生命並位於妮雅身邊。",
    fixture: true,
  },
  {
    id: "stage-10-near-defeat",
    stageId: "stage-10",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，克諾絲位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-10-victory-ready",
    stageId: "stage-10",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "全部追兵已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-10-cleared",
    stageId: "stage-10",
    title: "完成路由",
    phase: "Route to stage 12",
    description: "視為飛船追擊戰已完成，直接進入「落入沼澤」墜船關前劇情。",
    fixture: true,
  },
  {
    id: "stage-12-prebattle",
    stageId: "stage-12",
    title: "飛船墜落",
    phase: "SAY/0029",
    description: "查看怪物撞擊飛船、眾人墜入沼澤的 11 頁 BK/10–13 劇情。",
  },
  {
    id: "stage-12-deployment",
    stageId: "stage-12",
    title: "沼澤部署",
    phase: "1/9 initial",
    description: "直接開啟正式部署；妮雅固定，十九名候選最多選八人。",
  },
  {
    id: "stage-12-opening",
    stageId: "stage-12",
    title: "水戰士現身",
    phase: "SAY/0030",
    description: "完整九人部署後查看 BK/14 的沼澤著陸與水戰士現身對話。",
  },
  {
    id: "stage-12-player",
    stageId: "stage-12",
    title: "玩家回合",
    phase: "Round 1",
    description: "九人完整編隊進入玩家階段，對抗東側五個水戰士根單位。",
  },
  {
    id: "stage-12-split",
    stageId: "stage-12",
    title: "水戰士分裂",
    phase: "Shared-life split",
    description: "根槽 40 已受到一次普通近戰攻擊，展示一個共享生命的分裂身體。",
    fixture: true,
  },
  {
    id: "stage-12-near-victory",
    stageId: "stage-12",
    title: "最後一組水戰士",
    phase: "Eliminate side 2",
    description: "其餘四組已離場，最後一個水戰士根單位只剩 1 點生命並位於妮雅身邊。",
    fixture: true,
  },
  {
    id: "stage-12-near-defeat",
    stageId: "stage-12",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，水戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-12-victory-ready",
    stageId: "stage-12",
    title: "收服水戰士",
    phase: "SAY/0031",
    description: "全部水戰士已離場，直接驗證葛蒂拉斯收服水戰士的勝利對話與編號保存。",
    fixture: true,
  },
  {
    id: "stage-12-cleared",
    stageId: "stage-12",
    title: "完成路由",
    phase: "Route to stage 13",
    description: "視為沼澤戰已完成，停在「龍塔外」內部第 13 關凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-13-prebattle",
    stageId: "stage-13",
    title: "龍塔突擊會議",
    phase: "SAY/0032",
    description: "查看妮雅一行發現龍塔、決定派精銳小隊突擊的 10 頁 BK/15 劇情。",
  },
  {
    id: "stage-13-deployment",
    stageId: "stage-13",
    title: "龍塔外部署",
    phase: "1/12 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選十一人。",
  },
  {
    id: "stage-13-player",
    stageId: "stage-13",
    title: "玩家回合",
    phase: "Round 1",
    description: "十二人完整編隊進入玩家階段，對抗瑪西爾率領的九名龍塔守軍。",
  },
  {
    id: "stage-13-near-victory",
    stageId: "stage-13",
    title: "一擊擊敗瑪西爾",
    phase: "Leader victory 999",
    description: "瑪西爾只剩 1 點生命且位於妮雅身邊；其餘八名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-13-near-defeat",
    stageId: "stage-13",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方騎兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-13-victory-ready",
    stageId: "stage-13",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "瑪西爾已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-13-cleared",
    stageId: "stage-13",
    title: "完成路由",
    phase: "Route to stage 14",
    description: "視為龍塔外戰鬥已完成，停在「龍塔第一層」內部第 14 關凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-14-deployment",
    stageId: "stage-14",
    title: "龍塔第一層部署",
    phase: "1/10 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選九人。",
  },
  {
    id: "stage-14-opening",
    stageId: "stage-14",
    title: "芳攔截攻略隊",
    phase: "SAY/0033",
    description: "十人編隊開戰後播放芳、蘇蘭達與妮雅的五頁戰場對話。",
  },
  {
    id: "stage-14-player",
    stageId: "stage-14",
    title: "玩家回合",
    phase: "Round 1",
    description: "十人完整編隊進入玩家階段，對抗芳率領的七名龍塔第一層守軍。",
  },
  {
    id: "stage-14-near-victory",
    stageId: "stage-14",
    title: "一擊擊敗芳",
    phase: "Leader victory 999",
    description: "芳只剩 1 點生命且位於妮雅身邊；其餘六名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-14-near-defeat",
    stageId: "stage-14",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方神劍戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-14-victory-ready",
    stageId: "stage-14",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "芳已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-14-cleared",
    stageId: "stage-14",
    title: "完成路由",
    phase: "Route to stage 15",
    description: "視為龍塔第一層戰鬥已完成，停在「龍塔第二層」內部第 15 關凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-15-deployment",
    stageId: "stage-15",
    title: "龍塔第二層部署",
    phase: "1/10 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選九人。",
  },
  {
    id: "stage-15-opening",
    stageId: "stage-15",
    title: "蘭攔截攻略隊",
    phase: "SAY/0034",
    description: "十人編隊開戰後播放蘭、妮雅與蘇蘭達的五頁戰場對話。",
  },
  {
    id: "stage-15-player",
    stageId: "stage-15",
    title: "玩家回合",
    phase: "Round 1",
    description: "十人完整編隊進入玩家階段，對抗蘭率領的十名龍塔第二層守軍。",
  },
  {
    id: "stage-15-near-victory",
    stageId: "stage-15",
    title: "一擊擊敗蘭",
    phase: "Leader victory 999",
    description: "蘭只剩 1 點生命且位於妮雅身邊；其餘九名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-15-near-defeat",
    stageId: "stage-15",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方巨斧戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-15-victory-ready",
    stageId: "stage-15",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "蘭已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-15-cleared",
    stageId: "stage-15",
    title: "完成路由",
    phase: "Route to stage 16",
    description: "視為龍塔第二層戰鬥已完成，直接進入「龍塔第三層」內部第 16 關。",
    fixture: true,
  },
  {
    id: "stage-16-deployment",
    stageId: "stage-16",
    title: "龍塔第三層部署",
    phase: "1/10 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選九人。",
  },
  {
    id: "stage-16-opening",
    stageId: "stage-16",
    title: "莎攔截攻略隊",
    phase: "SAY/0035",
    description: "十人編隊開戰後播放莎的四頁戰場獨白。",
  },
  {
    id: "stage-16-player",
    stageId: "stage-16",
    title: "玩家回合",
    phase: "Round 1",
    description: "十人完整編隊進入玩家階段，對抗莎率領的十三名龍塔第三層守軍。",
  },
  {
    id: "stage-16-near-victory",
    stageId: "stage-16",
    title: "一擊擊敗莎",
    phase: "Leader victory 999",
    description: "莎只剩 1 點生命且位於妮雅身邊；其餘十二名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-16-near-defeat",
    stageId: "stage-16",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方神劍戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-16-victory-ready",
    stageId: "stage-16",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "莎已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-16-cleared",
    stageId: "stage-16",
    title: "完成路由",
    phase: "Route to stage 17",
    description: "視為龍塔第三層戰鬥已完成，直接進入「龍塔第四層」內部第 17 關。",
    fixture: true,
  },
  {
    id: "stage-17-deployment",
    stageId: "stage-17",
    title: "龍塔第四層部署",
    phase: "1/10 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選九人。",
  },
  {
    id: "stage-17-opening",
    stageId: "stage-17",
    title: "倩攔截攻略隊",
    phase: "SAY/0036",
    description: "十人編隊開戰後播放倩的三頁戰場獨白。",
  },
  {
    id: "stage-17-player",
    stageId: "stage-17",
    title: "玩家回合",
    phase: "Round 1",
    description: "十人完整編隊進入玩家階段，對抗倩率領的十二名龍塔第四層守軍。",
  },
  {
    id: "stage-17-near-victory",
    stageId: "stage-17",
    title: "一擊擊敗倩",
    phase: "Leader victory 999",
    description: "倩只剩 1 點生命且位於妮雅身邊；其餘十一名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-17-near-defeat",
    stageId: "stage-17",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方鎧甲戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-17-victory-ready",
    stageId: "stage-17",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "倩已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-17-cleared",
    stageId: "stage-17",
    title: "完成路由",
    phase: "Route to stage 18",
    description: "視為龍塔第四層戰鬥已完成，直接進入「龍塔第五層」內部第 18 關。",
    fixture: true,
  },
  {
    id: "stage-18-deployment",
    stageId: "stage-18",
    title: "龍塔第五層部署",
    phase: "1/8 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選七人。",
  },
  {
    id: "stage-18-opening",
    stageId: "stage-18",
    title: "麗攔截攻略隊",
    phase: "SAY/0037",
    description: "八人編隊開戰後播放麗與妮雅的三頁戰場對話。",
  },
  {
    id: "stage-18-player",
    stageId: "stage-18",
    title: "玩家回合",
    phase: "Round 1",
    description: "八人完整編隊進入玩家階段，對抗麗率領的十六名龍塔第五層守軍。",
  },
  {
    id: "stage-18-near-victory",
    stageId: "stage-18",
    title: "一擊擊敗麗",
    phase: "Leader victory 999",
    description: "麗只剩 1 點生命且位於妮雅身邊；其餘十五名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-18-near-defeat",
    stageId: "stage-18",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方神劍戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-18-victory-ready",
    stageId: "stage-18",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "麗已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-18-cleared",
    stageId: "stage-18",
    title: "完成路由",
    phase: "Route to stage 19",
    description: "視為龍塔第五層戰鬥已完成，直接進入「龍塔第六層」內部第 19 關。",
    fixture: true,
  },
  {
    id: "stage-19-deployment",
    stageId: "stage-19",
    title: "龍塔第六層部署",
    phase: "1/10 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選九人。",
  },
  {
    id: "stage-19-opening",
    stageId: "stage-19",
    title: "愛招攬攻略隊",
    phase: "SAY/0038",
    description: "十人編隊開戰後播放愛與蘇蘭達的四頁戰場對話。",
  },
  {
    id: "stage-19-player",
    stageId: "stage-19",
    title: "玩家回合",
    phase: "Round 1",
    description: "十人完整編隊進入玩家階段，對抗愛率領的二十一名龍塔第六層守軍。",
  },
  {
    id: "stage-19-near-victory",
    stageId: "stage-19",
    title: "一擊擊敗愛",
    phase: "Leader victory 999",
    description: "愛只剩 1 點生命且位於妮雅身邊；其餘二十名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-19-near-defeat",
    stageId: "stage-19",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方神劍戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-19-victory-ready",
    stageId: "stage-19",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "愛已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-19-cleared",
    stageId: "stage-19",
    title: "完成路由",
    phase: "Route to stage 20",
    description: "視為龍塔第六層戰鬥已完成，停在「龍塔頂部」內部第 20 關凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-20-prebattle",
    stageId: "stage-20",
    title: "龍塔頂部關前劇情",
    phase: "SAY/0039",
    description: "從正式入口播放抵達塔頂、發現巨門與巨門開啟的六頁劇情。",
  },
  {
    id: "stage-20-deployment",
    stageId: "stage-20",
    title: "龍塔頂部部署",
    phase: "3/17 initial",
    description: "守護者、妮雅與葛蒂拉斯固定；二十名候選最多選十四人。",
  },
  {
    id: "stage-20-opening",
    stageId: "stage-20",
    title: "半龍戰士包圍",
    phase: "SAY/0040",
    description: "十七人編隊開戰後，先顯示十六名半龍戰士的原版敘事陣形。",
  },
  {
    id: "stage-20-player",
    stageId: "stage-20",
    title: "妖龍玩家回合",
    phase: "Round 1 after SAY/0071",
    description: "守護者前移、十六名半龍戰士退場、妖龍登場後進入正式玩家階段。",
  },
  {
    id: "stage-20-near-victory",
    stageId: "stage-20",
    title: "一擊擊退妖龍",
    phase: "Dragon victory 999",
    description: "妖龍只剩 1 點生命且位於妮雅身邊，用於驗證琴斯與龍王的完整勝利演出。",
    fixture: true,
  },
  {
    id: "stage-20-near-defeat",
    stageId: "stage-20",
    title: "妮雅近敗",
    phase: "WD defeat setup",
    description: "妮雅只剩 1 點生命，妖龍位於 WD 選擇範圍內。",
    fixture: true,
  },
  {
    id: "stage-20-victory-ready",
    stageId: "stage-20",
    title: "勝利演出準備",
    phase: "Kins arrival and SAY/0072–0075",
    description: "妖龍已離場，直接驗證琴斯移動與四段戰後劇情。",
    fixture: true,
  },
  {
    id: "stage-20-cleared",
    stageId: "stage-20",
    title: "完成路由",
    phase: "Route to stage 21",
    description: "視為龍塔頂部戰鬥已完成，直接進入「焦土森林村莊外」第 21 關關前劇情。",
    fixture: true,
  },
  {
    id: "stage-21-prebattle",
    stageId: "stage-21",
    title: "焦土森林傳送前劇情",
    phase: "SAY/0042",
    description: "守護者請攻略隊整隊，隨後將眾人傳送到焦土森林村莊外。",
  },
  {
    id: "stage-21-cleared",
    stageId: "stage-21",
    title: "完成偵察路由",
    phase: "Route to stage 22",
    description: "視為四人偵察過場已完成，停在「焦土森林村莊中」內部第 22 關凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-22-deployment",
    stageId: "stage-22",
    title: "村莊部署",
    phase: "1/19 initial",
    description: "直接開啟正式部署；妮雅固定，二十七名候選最多選十八人，部署時不顯示伏兵。",
  },
  {
    id: "stage-22-opening",
    stageId: "stage-22",
    title: "重逢與伏擊",
    phase: "SAY/0076–0079",
    description: "十九人編隊完成部署，依序播放維絲塔、琴斯、葛蒂拉斯與妖龍的第 1 回合演出。",
  },
  {
    id: "stage-22-player",
    stageId: "stage-22",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過伏擊演出，保留原生妖龍焦點，直接迎戰妖龍與五名魔祭師；臨時劇情單位已離場。",
  },
  {
    id: "stage-22-near-victory",
    stageId: "stage-22",
    title: "一擊擊敗妖龍",
    phase: "Victory slot 28",
    description: "妖龍只剩 1 點生命且位於妮雅身邊；其他魔祭師仍在場，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-22-near-defeat",
    stageId: "stage-22",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，葛蒂拉斯位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-22-victory-ready",
    stageId: "stage-22",
    title: "關後整頓",
    phase: "SAY/0045",
    description: "妖龍已離場，在第 22 關戰場上播放傷員整頓對話，完成後才進入勝利回饋與存檔。",
    fixture: true,
  },
  {
    id: "stage-22-cleared",
    stageId: "stage-22",
    title: "完成路由",
    phase: "Route to stage 23",
    description: "視為焦土森林村莊的關後整頓與存檔已完成，直接進入「死亡之谷中」部署。",
    fixture: true,
  },
  {
    id: "stage-23-deployment",
    stageId: "stage-23",
    title: "死亡之谷部署",
    phase: "1/15 initial",
    description: "妮雅固定，二十八名候選最多選十四人；部署預覽顯示二十一名靜態守軍。",
  },
  {
    id: "stage-23-opening",
    stageId: "stage-23",
    title: "突圍開場",
    phase: "SAY/0046",
    description: "十五人編隊完成部署，播放保持體力、無需全滅守軍的開場對白。",
  },
  {
    id: "stage-23-player",
    stageId: "stage-23",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場對白，直接驗證二十一名守軍的原版行為分組與妮雅突圍目標。",
  },
  {
    id: "stage-23-near-victory",
    stageId: "stage-23",
    title: "一步抵達頂端",
    phase: "Victory cell range 0–524",
    description: "妮雅位於頂端目標區下一格，向上移動一步即可在守軍仍存活時獲勝。",
    fixture: true,
  },
  {
    id: "stage-23-near-defeat",
    stageId: "stage-23",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，一名半龍戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-23-victory-ready",
    stageId: "stage-23",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "守軍仍全員在場，直接驗證妮雅抵達頂端後的普通勝利回饋與第 24 關路由。",
    fixture: true,
  },
  {
    id: "stage-23-cleared",
    stageId: "stage-23",
    title: "完成路由",
    phase: "Route to stage 24",
    description: "視為死亡之谷突圍已完成，直接進入「死亡之谷城堡前」部署。",
    fixture: true,
  },
  {
    id: "stage-24-deployment",
    stageId: "stage-24",
    title: "城堡前部署",
    phase: "1/15 initial",
    description: "妮雅固定，二十八名候選最多選十四人；部署預覽顯示二十二名靜態守軍。",
  },
  {
    id: "stage-24-opening",
    stageId: "stage-24",
    title: "城堡前開場",
    phase: "SAY/0047",
    description: "十五人編隊完成部署，播放希蜜、蘇蘭達、琴斯與妮雅面對城堡的開場對白。",
  },
  {
    id: "stage-24-player",
    stageId: "stage-24",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場對白，直接驗證二十二名守軍與妮雅抵達城堡的線性格號目標。",
  },
  {
    id: "stage-24-near-victory",
    stageId: "stage-24",
    title: "一步抵達城堡",
    phase: "Victory cell range 0–1030",
    description: "妮雅位於目標區右側一格，向左移動一步即可在守軍仍存活時獲勝。",
    fixture: true,
  },
  {
    id: "stage-24-near-defeat",
    stageId: "stage-24",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，獸骨騎士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-24-victory-ready",
    stageId: "stage-24",
    title: "勝利對白",
    phase: "SAY/0048",
    description: "守軍仍全員在場，直接驗證妮雅抵達城堡後的九段勝利對白。",
    fixture: true,
  },
  {
    id: "stage-24-cleared",
    stageId: "stage-24",
    title: "完成路由",
    phase: "Route to stage 26",
    description: "視為城堡前戰鬥已完成，直接進入第 25 個可玩關卡「遭遇碧娜維姬」部署；原版內部編號跳至 stage 26。",
    fixture: true,
  },
  {
    id: "stage-26-deployment",
    stageId: "stage-26",
    title: "碧娜維姬戰部署",
    phase: "4/22 initial",
    description: "希蜜、妮雅、蘇蘭達與琴斯固定，二十五名候選最多選十八人；部署預覽顯示八名靜態敵軍。",
  },
  {
    id: "stage-26-opening",
    stageId: "stage-26",
    title: "碧娜維姬戰開場",
    phase: "SAY/0049",
    description: "二十二人編隊完成部署，播放碧娜維姬的黑魔法與琴斯反咒說明。",
  },
  {
    id: "stage-26-player",
    stageId: "stage-26",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場對白，直接迎戰碧娜維姬與七名魔法祭司。",
  },
  {
    id: "stage-26-enemy-tail",
    stageId: "stage-26",
    title: "敵方回合列推移",
    phase: "Enemy phase tail ×2",
    description: "妮雅置於魔法掃描帶內；結束玩家回合即可驗證兩次完整演出及每次演出後的向下推移。",
    fixture: true,
  },
  {
    id: "stage-26-near-victory",
    stageId: "stage-26",
    title: "一擊擊敗碧娜維姬",
    phase: "Victory slot 1",
    description: "碧娜維姬只剩 1 點生命且位於妮雅身邊；其餘七名祭司仍在場。",
    fixture: true,
  },
  {
    id: "stage-26-near-defeat",
    stageId: "stage-26",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，一名魔法祭司位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-26-victory-ready",
    stageId: "stage-26",
    title: "勝利對白",
    phase: "SAY/0050",
    description: "碧娜維姬已離場，直接驗證黑魔石與返回瓦爾克麗城的三十四段勝利對白。",
    fixture: true,
  },
  {
    id: "stage-26-cleared",
    stageId: "stage-26",
    title: "完成路由",
    phase: "Route to stage 27",
    description: "視為碧娜維姬戰已完成，直接進入「趕回瓦爾克麗城」部署。",
    fixture: true,
  },
  {
    id: "stage-27-deployment",
    stageId: "stage-27",
    title: "瓦爾克麗回城戰部署",
    phase: "11/31 initial",
    description: "妮雅、三名工兵與七名城防友軍固定，二十八名候選最多選二十人；部署預覽顯示五名靜態叛軍。",
  },
  {
    id: "stage-27-opening",
    stageId: "stage-27",
    title: "瓦爾克麗回城戰開場",
    phase: "SAY/0051",
    description: "三十一人編隊完成部署，播放守城士兵迎接女帝與妮雅的六段對白。",
  },
  {
    id: "stage-27-player",
    stageId: "stage-27",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場對白，玩家控制妮雅、三名工兵與二十名候選；七名城防友軍在手動階段後自動行動。",
  },
  {
    id: "stage-27-ally-auto",
    stageId: "stage-27",
    title: "城防友軍自動階段",
    phase: "Ally auto",
    description: "玩家隊已全部行動；結束回合後驗證七名行為 2 城防友軍使用共享專家 AI。",
    fixture: true,
  },
  {
    id: "stage-27-near-victory",
    stageId: "stage-27",
    title: "一步回到瓦爾克麗城",
    phase: "Victory range",
    description: "妮雅位於城區下一格；上移一步即可進入精確線性目標區，五名叛軍仍在場。",
    fixture: true,
  },
  {
    id: "stage-27-near-defeat",
    stageId: "stage-27",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，一名魔劍戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-27-victory-ready",
    stageId: "stage-27",
    title: "勝利對白",
    phase: "SAY/0052",
    description: "五名叛軍仍在場，直接驗證瓦爾克麗危機化解後的十段勝利對白。",
    fixture: true,
  },
  {
    id: "stage-27-cleared",
    stageId: "stage-27",
    title: "完成路由",
    phase: "Route to stage 28",
    description: "視為瓦爾克麗回城戰已完成，直接進入「保衛瓦爾克麗城」關前戰議。",
    fixture: true,
  },
  {
    id: "stage-28-prebattle",
    stageId: "stage-28",
    title: "關前戰議",
    phase: "SAY/0053",
    description: "在 BK/22 大殿播放妮雅重新部署兵力與調查四騎士的十四段關前對白。",
  },
  {
    id: "stage-28-deployment",
    stageId: "stage-28",
    title: "瓦爾克麗守城戰部署",
    phase: "1/29 initial",
    description: "妮雅固定出場，二十八名候選最多全員出擊；部署預覽顯示十七名靜態攻城敵軍。",
  },
  {
    id: "stage-28-opening",
    stageId: "stage-28",
    title: "瓦爾克麗守城戰開場",
    phase: "SAY/0054",
    description: "二十九人編隊完成部署，播放拉朵那通報攻城軍逼近的五段開戰對白。",
  },
  {
    id: "stage-28-player",
    stageId: "stage-28",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過關前與開場對白，以二十九人守城隊迎戰十七名共享專家追擊敵軍。",
  },
  {
    id: "stage-28-near-victory",
    stageId: "stage-28",
    title: "一擊全滅攻城軍",
    phase: "Victory setup",
    description: "只保留 1 點生命的最後一名魔劍戰士，妮雅近戰一次即可完成全滅目標。",
    fixture: true,
  },
  {
    id: "stage-28-near-defeat",
    stageId: "stage-28",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，一名魔劍戰士位於相鄰格；重試回到完整關前戰議。",
    fixture: true,
  },
  {
    id: "stage-28-victory-ready",
    stageId: "stage-28",
    title: "勝利對白",
    phase: "SAY/0055",
    description: "十七名攻城敵軍已全數離場，直接驗證突破包圍與四騎士情報的八段勝利對白。",
    fixture: true,
  },
  {
    id: "stage-28-cleared",
    stageId: "stage-28",
    title: "完成路由",
    phase: "Route to stage 29",
    description: "視為瓦爾克麗守城戰已完成，顯示「騎士城堡前」的 stage 29 完成邊界。",
    fixture: true,
  },
  {
    id: "stage-29-prebattle",
    stageId: "stage-29",
    title: "騎士城堡關前進軍",
    phase: "SAY/0056",
    description: "在 BK/23 播放進攻騎士城堡與提防艾西柯羅的七段關前對白。",
  },
  {
    id: "stage-29-deployment",
    stageId: "stage-29",
    title: "騎士城堡前部署",
    phase: "1/15 initial",
    description: "妮雅固定，二十九名候選最多選十四人；槽 22 名單卡顯示愛莉歐拉，預覽十五名靜態守軍。",
  },
  {
    id: "stage-29-player",
    stageId: "stage-29",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過關前對白，以十五人進攻隊迎戰十五名共享專家追擊守軍；沒有開場對白。",
  },
  {
    id: "stage-29-near-victory",
    stageId: "stage-29",
    title: "一擊全滅城堡守軍",
    phase: "Victory setup",
    description: "只保留 1 點生命的最後一名魔弓兵，妮雅近戰一次即可完成全滅目標。",
    fixture: true,
  },
  {
    id: "stage-29-near-defeat",
    stageId: "stage-29",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，艾西柯羅位於相鄰格；重試回到完整關前進軍。",
    fixture: true,
  },
  {
    id: "stage-29-victory-ready",
    stageId: "stage-29",
    title: "普通勝利結算",
    phase: "Victory feedback",
    description: "十五名守軍已全數離場，直接驗證沒有勝利 SAY 的普通回饋與保存流程。",
    fixture: true,
  },
  {
    id: "stage-29-cleared",
    stageId: "stage-29",
    title: "完成路由",
    phase: "Route to stage 30",
    description: "視為騎士城堡戰已完成，直接進入「治癒維斯塔女帝」的 stage 30 關前劇情。",
    fixture: true,
  },
  {
    id: "stage-30-prebattle",
    stageId: "stage-30",
    title: "救治女帝關前",
    phase: "SAY/0057",
    description: "在 BK/23 播放女帝失控、妮雅與琴斯趕回瓦爾克麗的十七段關前對白。",
  },
  {
    id: "stage-30-player",
    stageId: "stage-30",
    title: "士兵形態玩家回合",
    phase: "Round 1",
    description: "跳過關前與開場對白，以固定三人迎戰滿生命、經驗 0 的維絲塔士兵形態。",
    fixture: true,
  },
  {
    id: "stage-30-near-victory",
    stageId: "stage-30",
    title: "難度末形態一擊歸隊",
    phase: "Final form",
    description: "依目前難度載入第 8／16／24／32 個末形態；只剩 1 點生命，妮雅一擊後轉為我方女帝。",
    fixture: true,
  },
  {
    id: "stage-30-near-defeat",
    stageId: "stage-30",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，維絲塔士兵形態位於相鄰格；重試返回完整關前劇情。",
    fixture: true,
  },
  {
    id: "stage-30-victory-ready",
    stageId: "stage-30",
    title: "女帝恢復對白",
    phase: "SAY/0059",
    description: "直接進入女帝恢復後的六段勝利對白，驗證普通回饋與保存流程。",
    fixture: true,
  },
  {
    id: "stage-30-cleared",
    stageId: "stage-30",
    title: "完成路由",
    phase: "Route to stage 31",
    description: "視為女帝救治完成，直接進入「前往斯德林海峽」的關前流程。",
    fixture: true,
  },
  {
    id: "stage-31-prebattle",
    stageId: "stage-31",
    title: "斯德林海峽關前",
    phase: "SAY/0060",
    description: "在 BK/23 播放妮雅歸隊、確認菲伊魯茵位置並下令渡海的十四段關前對白。",
  },
  {
    id: "stage-31-deployment",
    stageId: "stage-31",
    title: "渡海部隊部署",
    phase: "Deployment",
    description: "五名固定角色與二十四名候選使用十二格，最多組成十七人渡海隊。",
    fixture: true,
  },
  {
    id: "stage-31-player",
    stageId: "stage-31",
    title: "伏擊後玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0060／0061，以十七人渡海隊迎戰菲伊魯茵與十四名伏兵。",
    fixture: true,
  },
  {
    id: "stage-31-near-victory",
    stageId: "stage-31",
    title: "一擊擊破最後伏兵",
    phase: "Victory setup",
    description: "只保留 1 點生命的菲伊魯茵，妮雅近戰一次即可完成全滅目標。",
    fixture: true,
  },
  {
    id: "stage-31-near-defeat",
    stageId: "stage-31",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，菲伊魯茵位於相鄰格；重試回到完整關前流程。",
    fixture: true,
  },
  {
    id: "stage-31-victory-ready",
    stageId: "stage-31",
    title: "菲伊魯茵撤退對白",
    phase: "SAY/0062",
    description: "十五名伏兵已離場，直接驗證兩段勝利對白、普通回饋與保存流程。",
    fixture: true,
  },
  {
    id: "stage-31-cleared",
    stageId: "stage-31",
    title: "完成路由",
    phase: "Route to stage 32",
    description: "視為斯德林海峽伏擊戰已完成，直接進入下一場「斯德林海峽」部署。",
    fixture: true,
  },
  {
    id: "stage-32-deployment",
    stageId: "stage-32",
    title: "海峽聯軍戰部署",
    phase: "Deployment",
    description: "妮雅固定出場，二十八名候選使用十五格，最多組成十六人追擊隊。",
    fixture: true,
  },
  {
    id: "stage-32-player",
    stageId: "stage-32",
    title: "聯軍現身後玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0063，以十六人追擊隊迎戰菲伊魯茵、芙瑪羅妮及十六名靜態開局敵軍。",
    fixture: true,
  },
  {
    id: "stage-32-near-victory",
    stageId: "stage-32",
    title: "一擊擊破最後敵軍",
    phase: "Victory setup",
    description: "只保留 1 點生命的菲伊魯茵，妮雅近戰一次即可完成全滅目標。",
    fixture: true,
  },
  {
    id: "stage-32-near-defeat",
    stageId: "stage-32",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，菲伊魯茵位於相鄰格；重試直接返回本關部署。",
    fixture: true,
  },
  {
    id: "stage-32-victory-ready",
    stageId: "stage-32",
    title: "拉那洛城進軍對白",
    phase: "SAY/0064",
    description: "十八名敵軍已離場，直接驗證四段勝利對白、普通回饋與保存流程。",
    fixture: true,
  },
  {
    id: "stage-32-cleared",
    stageId: "stage-32",
    title: "完成路由",
    phase: "Route to stage 33",
    description: "視為海峽聯軍戰已完成，直接進入下一場「拉那洛城外」部署。",
    fixture: true,
  },
  {
    id: "stage-33-deployment",
    stageId: "stage-33",
    title: "城外攻堅部署",
    phase: "Deployment",
    description: "妮雅固定出場，二十八名候選使用九格，最多組成十人攻城隊。",
    fixture: true,
  },
  {
    id: "stage-33-player",
    stageId: "stage-33",
    title: "城外守軍現身後玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0065，以十人攻城隊迎戰二十九名靜態開局守軍。",
    fixture: true,
  },
  {
    id: "stage-33-near-victory",
    stageId: "stage-33",
    title: "一擊擊破最後守軍",
    phase: "Victory setup",
    description: "只保留 1 點生命的城外守軍，妮雅近戰一次即可完成全滅目標。",
    fixture: true,
  },
  {
    id: "stage-33-near-defeat",
    stageId: "stage-33",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，城外守軍位於相鄰格；重試直接返回本關部署。",
    fixture: true,
  },
  {
    id: "stage-33-victory-ready",
    stageId: "stage-33",
    title: "城外守軍全滅",
    phase: "Victory",
    description: "二十九名守軍已離場，驗證無勝利對白的普通回饋、保存與進城路由。",
    fixture: true,
  },
  {
    id: "stage-33-cleared",
    stageId: "stage-33",
    title: "完成路由",
    phase: "Route to stage 34",
    description: "視為拉那洛城外攻堅戰已完成，直接進入下一個「拉那洛城內」部署。",
    fixture: true,
  },
  {
    id: "stage-34-deployment",
    stageId: "stage-34",
    title: "城內攻堅部署",
    phase: "Deployment",
    description: "妮雅固定出場，二十八名候選使用左右十格，最多組成十一人攻堅隊。",
    fixture: true,
  },
  {
    id: "stage-34-player",
    stageId: "stage-34",
    title: "蕾娜吉芙宣戰後玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0066，以十一人攻堅隊迎戰十九名靜態開局敵軍。",
    fixture: true,
  },
  {
    id: "stage-34-near-victory",
    stageId: "stage-34",
    title: "一擊擊破最後敵軍",
    phase: "Victory setup",
    description: "只保留 1 點生命的城內敵軍，妮雅近戰一次即可完成全滅目標。",
    fixture: true,
  },
  {
    id: "stage-34-near-defeat",
    stageId: "stage-34",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，城內敵軍位於相鄰格；重試直接返回本關部署。",
    fixture: true,
  },
  {
    id: "stage-34-victory-ready",
    stageId: "stage-34",
    title: "城內敵軍全滅",
    phase: "Victory",
    description: "十九名敵軍已離場，驗證無勝利對白的普通回饋、保存與時空異變路由。",
    fixture: true,
  },
  {
    id: "stage-34-cleared",
    stageId: "stage-34",
    title: "完成路由",
    phase: "Route to stage 35",
    description: "視為拉那洛城內攻堅戰已完成，直接進入下一個「時空異變」開場對白。",
    fixture: true,
  },
  {
    id: "stage-35-opening",
    stageId: "stage-35",
    title: "異世界之門異變",
    phase: "SAY/0067",
    description: "固定九人編隊進場，播放異世界之門與死亡之谷部隊湧出的開場對白。",
    fixture: true,
  },
  {
    id: "stage-35-player",
    stageId: "stage-35",
    title: "開場對白後玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0067，以九人固定編隊迎戰十名行為 12 的原地待命敵軍。",
    fixture: true,
  },
  {
    id: "stage-35-near-victory",
    stageId: "stage-35",
    title: "一擊擊破最後敵軍",
    phase: "Victory setup",
    description: "只保留 1 點生命的死亡之谷士兵，妮雅近戰一次即可完成全滅目標。",
    fixture: true,
  },
  {
    id: "stage-35-near-defeat",
    stageId: "stage-35",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，死亡之谷士兵位於相鄰格；重試重播本關開場。",
    fixture: true,
  },
  {
    id: "stage-35-victory-ready",
    stageId: "stage-35",
    title: "死亡之谷部隊全滅",
    phase: "SAY/0068",
    description: "十名敵軍已離場，驗證逃難真相對白、普通回饋、保存與第 36 關路由。",
    fixture: true,
  },
  {
    id: "stage-35-cleared",
    stageId: "stage-35",
    title: "完成路由",
    phase: "Route to stage 36",
    description: "視為時空異變戰鬥已完成，直接進入下一個「異世界的碧娜維姬」部署。",
    fixture: true,
  },
  {
    id: "stage-36-deployment",
    stageId: "stage-36",
    title: "異世界追擊隊部署",
    phase: "Deployment",
    description: "妮雅固定出場，二十八名候選使用二十七個開放格，最多組成二十八人追擊隊。",
    fixture: true,
  },
  {
    id: "stage-36-player",
    stageId: "stage-36",
    title: "碧娜維姬宣戰後玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0080，以二十八人追擊隊迎戰碧娜維姬與二十九名異世界敵軍。",
    fixture: true,
  },
  {
    id: "stage-36-near-victory",
    stageId: "stage-36",
    title: "一擊擊破碧娜維姬",
    phase: "Victory setup",
    description: "碧娜維姬只剩 1 點生命；無須清除其餘敵軍即可完成首領目標。",
    fixture: true,
  },
  {
    id: "stage-36-near-defeat",
    stageId: "stage-36",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，碧娜維姬位於相鄰格；重試直接返回本關部署。",
    fixture: true,
  },
  {
    id: "stage-36-victory-ready",
    stageId: "stage-36",
    title: "碧娜維姬已敗",
    phase: "Victory",
    description: "首領已離場，驗證無勝利對白的普通回饋、保存與第 37 關凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-36-cleared",
    stageId: "stage-36",
    title: "完成路由",
    phase: "Route to stage 37",
    description: "視為異世界追擊戰已完成，顯示下一個「究極女神」凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-37-deployment",
    stageId: "stage-37",
    title: "究極女神決戰部署",
    phase: "Deployment",
    description: "妮雅固定出場，二十八名候選使用二十六個開放格，最多組成二十七人決戰隊。",
    fixture: true,
  },
  {
    id: "stage-37-player",
    stageId: "stage-37",
    title: "吸收完成後玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0081，以二十七人決戰隊迎戰頭與兩隻手。",
    fixture: true,
  },
  {
    id: "stage-37-status-audit",
    stageId: "stage-37",
    title: "負面狀態／控制查驗",
    phase: "Round 1",
    description: "多莉可施放禁咒，驗證頭／手寫入狀態但專屬行動不受封鎖。",
    fixture: true,
  },
  {
    id: "stage-37-near-victory",
    stageId: "stage-37",
    title: "三部位近乎擊破",
    phase: "Victory setup",
    description: "頭與兩隻手各剩 1 點生命，驗證必須全部離場才獲勝。",
    fixture: true,
  },
  {
    id: "stage-37-near-defeat",
    stageId: "stage-37",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命；失敗後直接返回本關部署。",
    fixture: true,
  },
  {
    id: "stage-37-victory-ready",
    stageId: "stage-37",
    title: "三部位已敗",
    phase: "Victory",
    description: "究極女神三部位已全部離場，驗證普通回饋、保存與內部 stage 49 結局邊界。",
    fixture: true,
  },
  {
    id: "stage-37-cleared",
    stageId: "stage-37",
    title: "完成路由",
    phase: "Route to stage 49",
    description: "視為究極女神決戰已完成，顯示主線結局鏈凍結邊界。",
    fixture: true,
  },
] as const satisfies readonly DebugScenarioDefinition[];

export type DebugScenarioId = typeof DEBUG_SCENARIOS[number]["id"];

export function isDebugScenarioId(value: unknown): value is DebugScenarioId {
  return typeof value === "string"
    && DEBUG_SCENARIOS.some(({ id }) => id === value);
}

export function debugScenarioUrl(
  id: DebugScenarioId,
  difficulty: Difficulty,
  rosterSourceId?: DebugRosterSourceId,
  perStageGrowth?: number,
): string {
  const parameters = new URLSearchParams({ debugScenario: id, difficulty: String(difficulty) });
  if (rosterSourceId) parameters.set("roster", rosterSourceId);
  if (perStageGrowth !== undefined) {
    parameters.set("growth", String(perStageGrowth));
  }
  return `/?${parameters.toString()}`;
}
