import type { Difficulty, StageId } from "./types";
import { STAGE_RUNTIME_MANIFEST } from "./stage-runtime";
import type { DebugRosterSourceId } from "./debug-roster-profiles";

export interface DebugScenarioDefinition {
  id: string;
  stageId: StageId;
  title: string;
  phase: string;
  description: string;
  fixture?: boolean;
}

export function debugStageLabel(stageId: StageId): string {
  const stage = STAGE_RUNTIME_MANIFEST[stageId];
  return `第 ${stage.ordinal} 關 · ${stage.label}`;
}

export const DEBUG_SCENARIOS = [
  {
    id: "stage-00-prebattle",
    stageId: "stage-00",
    title: "關前劇情",
    phase: "SAY/0000",
    description: "從本關最初狀態開始，保留劇情、腳本移動和開戰對白。",
  },
  {
    id: "stage-00-player",
    stageId: "stage-00",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過關前演出，直接進入完整初始戰場的玩家階段。",
  },
  {
    id: "stage-00-near-victory",
    stageId: "stage-00",
    title: "一擊勝利",
    phase: "Victory setup",
    description: "只保留 1 點生命的最後敵人，攻擊一次即可驗證勝利流程。",
    fixture: true,
  },
  {
    id: "stage-00-cleared",
    stageId: "stage-00",
    title: "直接通關",
    phase: "Route to stage 1",
    description: "視為第 0 關已經完成，直接進入第 1 關關前劇情。",
    fixture: true,
  },
  {
    id: "stage-01-prebattle",
    stageId: "stage-01",
    title: "關前劇情",
    phase: "SAY/0004",
    description: "以完整戰役 roster 進入第 1 關關前劇情。",
  },
  {
    id: "stage-01-deployment",
    stageId: "stage-01",
    title: "部署",
    phase: "5/8 initial",
    description: "直接開啟正式部署介面，保留固定、可選、空位和錯誤規則。",
  },
  {
    id: "stage-01-player",
    stageId: "stage-01",
    title: "玩家回合",
    phase: "Round 1",
    description: "用六人編隊直接開戰，葛蒂拉斯已經部署。",
  },
  {
    id: "stage-01-magician",
    stageId: "stage-01",
    title: "魔術士技能靶場",
    phase: "1F / 1L / 1C",
    description: "追擊型敵兵位於冰雪最外圈，可驗證 REMAKE-036 外推到值 0，並只跳過一次敵方行動。",
    fixture: true,
  },
  {
    id: "stage-01-dispel",
    stageId: "stage-01",
    title: "冰封／破邪靶場",
    phase: "TR / REMAKE-013",
    description: "魔祭師可對相鄰冰封友軍施展破邪，驗證攻擊／治療不可選與演出後解封。",
    fixture: true,
  },
  {
    id: "stage-01-enemy-sister",
    stageId: "stage-01",
    title: "敵方修女範圍",
    phase: "Unified range 5",
    description: "敵方修女位於統一炎暴範圍 5 的邊界，結束回合即可觀察施法。",
    fixture: true,
  },
  {
    id: "stage-01-near-victory",
    stageId: "stage-01",
    title: "一擊擊敗芳",
    phase: "Victory 999",
    description: "芳只剩 1 點生命且位於妮雅身邊，攻擊一次進入傳令兵流程。",
    fixture: true,
  },
  {
    id: "stage-01-cleared",
    stageId: "stage-01",
    title: "直接通關",
    phase: "Route to stage 2",
    description: "視為第 1 關已經完成，直接進入第 2 關開場事件。",
    fixture: true,
  },
  {
    id: "stage-02-prebattle",
    stageId: "stage-02",
    title: "關前／開場敘事",
    phase: "SAY/0155",
    description: "由第 1 關完成 roster 建立固定戰場，保留第 1 回合開場敘事。",
  },
  {
    id: "stage-02-preparation",
    stageId: "stage-02",
    title: "固定編隊準備",
    phase: "Fixed 9 vs 5",
    description: "顯示完整固定陣容與自動友軍標記；本關沒有交互部署。",
  },
  {
    id: "stage-02-player",
    stageId: "stage-02",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場敘事，直接驗證三名手動角色與六名自動友軍。",
  },
  {
    id: "stage-02-near-victory",
    stageId: "stage-02",
    title: "一擊擊敗蘭",
    phase: "Victory 999",
    description: "蘭只剩 1 點生命且位於妮雅身邊，攻擊一次進入 SAY/0175。",
    fixture: true,
  },
  {
    id: "stage-02-cleared",
    stageId: "stage-02",
    title: "完成路由",
    phase: "Route to stage 3",
    description: "視為第 2 關已完成，直接進入第 3 關開場事件。",
    fixture: true,
  },
  {
    id: "stage-03-prebattle",
    stageId: "stage-03",
    title: "關前／開場敘事",
    phase: "SAY/0012",
    description: "由第 2 關完成 roster 建立固定戰場，保留希蜜與第四軍團會合敘事。",
  },
  {
    id: "stage-03-preparation",
    stageId: "stage-03",
    title: "固定編隊準備",
    phase: "Fixed 13 vs 12",
    description: "顯示完整固定陣容、黛西領隊與跟隨者；本關沒有交互部署。",
  },
  {
    id: "stage-03-player",
    stageId: "stage-03",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過開場敘事，直接驗證希蜜軍團與第四軍團的手動／自動分工。",
  },
  {
    id: "stage-03-near-victory",
    stageId: "stage-03",
    title: "一擊擊敗莎",
    phase: "Victory 999",
    description: "莎只剩 1 點生命且位於可控主將身邊，攻擊一次進入 SAY/0013。",
    fixture: true,
  },
  {
    id: "stage-03-cleared",
    stageId: "stage-03",
    title: "完成路由",
    phase: "Route to stage 4",
    description: "視為第 3 關已完成，直接進入第 4 關關前劇情。",
    fixture: true,
  },
  {
    id: "stage-04-prebattle",
    stageId: "stage-04",
    title: "關前劇情",
    phase: "SAY/0007",
    description: "從本關最初狀態開始，保留騎士團堡外的完整關前劇情。",
  },
  {
    id: "stage-04-deployment",
    stageId: "stage-04",
    title: "結界部署",
    phase: "2/8 initial",
    description: "直接開啟正式部署介面，標示首輪安全區與兩個危險空位。",
  },
  {
    id: "stage-04-player",
    stageId: "stage-04",
    title: "玩家回合",
    phase: "Round 1",
    description: "以八人編隊直接開戰，葛蒂拉斯由獨立友軍 AI 控制。",
  },
  {
    id: "stage-04-first-pulse",
    stageId: "stage-04",
    title: "首輪力場脈衝",
    phase: "Behavior 12 / MAGIC 26",
    description: "八人全編隊保留兩名結界外角色，用於驗證移動後必定發動的生命減半與原版動畫。",
    fixture: true,
  },
  {
    id: "stage-04-near-victory",
    stageId: "stage-04",
    title: "一步抵達出口",
    phase: "Victory 999",
    description: "葛蒂拉斯距出口一次獨立行動，結束玩家回合即可進入 SAY/0174。",
    fixture: true,
  },
  {
    id: "stage-04-cleared",
    stageId: "stage-04",
    title: "完成路由",
    phase: "Route to stage 5",
    description: "視為第 4 關已完成，直接進入第 5 關內殿部署。",
    fixture: true,
  },
  {
    id: "stage-05-deployment",
    stageId: "stage-05",
    title: "內殿部署",
    phase: "1/6 initial",
    description: "直接開啟正式部署；妮雅固定，七名候選最多選五人。",
  },
  {
    id: "stage-05-player",
    stageId: "stage-05",
    title: "玩家回合",
    phase: "Round 1",
    description: "六人編隊直接進入玩家階段，保留十四名敵軍與雙首領目標。",
  },
  {
    id: "stage-05-near-tintachi",
    stageId: "stage-05",
    title: "一擊擊敗汀塔琪",
    phase: "Victory slot 25",
    description: "汀塔琪只剩 1 點生命且位於妮雅身邊；萊茵仍在場。",
    fixture: true,
  },
  {
    id: "stage-05-near-rhein",
    stageId: "stage-05",
    title: "一擊擊敗萊茵",
    phase: "Victory slot 26",
    description: "萊茵只剩 1 點生命且位於妮雅身邊；汀塔琪仍在場。",
    fixture: true,
  },
  {
    id: "stage-05-near-defeat",
    stageId: "stage-05",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-05-victory-ready",
    stageId: "stage-05",
    title: "勝利準備",
    phase: "SAY/0010",
    description: "汀塔琪已離場，直接驗證恢復神志劇情、勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-05-cleared",
    stageId: "stage-05",
    title: "完成路由",
    phase: "Route to scene 42",
    description: "模擬第 5 關完成檔，建立現場傳送門過場且不重播 SAY/0010。",
    fixture: true,
  },
  {
    id: "stage-42-portal-live",
    stageId: "stage-42-portal",
    title: "傳送門現場",
    phase: "Live 999 timeline",
    description: "從 B/0085 台陣開始，播放兩次移動、四段劇情、完整究級落雷與離場。",
    fixture: true,
  },
  {
    id: "stage-42-completed-route",
    stageId: "stage-42-portal",
    title: "傳送門完成路由",
    phase: "Loaded 1000",
    description: "不重播傳送門表現或棋盤修改，直接進入第 6 關部署。",
    fixture: true,
  },
  {
    id: "stage-06-deployment",
    stageId: "stage-06",
    title: "異世界部署",
    phase: "1/9 initial",
    description: "直接開啟正式部署；妮雅固定，十二名候選最多選八人。",
  },
  {
    id: "stage-06-prebattle",
    stageId: "stage-06",
    title: "關前劇情",
    phase: "SAY/0014",
    description: "以九人編隊完成部署，播放異世界森林與騎士團追擊劇情。",
  },
  {
    id: "stage-06-player",
    stageId: "stage-06",
    title: "玩家回合",
    phase: "Round 1",
    description: "跳過 SAY/0014、SAY/0015，以九人編隊直接迎戰西艾蕾追擊隊。",
  },
  {
    id: "stage-06-near-xielei",
    stageId: "stage-06",
    title: "一擊擊敗西艾蕾",
    phase: "Victory slot 19",
    description: "西艾蕾只剩 1 點生命且位於妮雅身邊；其餘追擊隊已離場。",
    fixture: true,
  },
  {
    id: "stage-06-near-defeat",
    stageId: "stage-06",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-06-victory-ready",
    stageId: "stage-06",
    title: "勝利準備",
    phase: "SAY/0016",
    description: "西艾蕾已離場，直接驗證撤退劇情、游騎兵台陣、領隊移動與 SAY/0115。",
    fixture: true,
  },
  {
    id: "stage-06-cleared",
    stageId: "stage-06",
    title: "完成路由",
    phase: "Route to stage 7",
    description: "視為第 6 關已完成，直接進入第 7 關營地劇情。",
    fixture: true,
  },
  {
    id: "stage-07-prebattle",
    stageId: "stage-07",
    title: "關前劇情",
    phase: "SAY/0017",
    description: "從本關最初狀態開始，保留游騎兵營地白天／夜間的雙背景劇情。",
  },
  {
    id: "stage-07-deployment",
    stageId: "stage-07",
    title: "營地守備部署",
    phase: "2/7 initial",
    description: "直接開啟正式部署；妮雅、希蜜固定，十一名候選最多選五人。",
  },
  {
    id: "stage-07-player",
    stageId: "stage-07",
    title: "玩家回合",
    phase: "Round 1",
    description: "七人編隊直接進入玩家階段，保留十一名敵軍與萊莉首領目標。",
  },
  {
    id: "stage-07-near-laili",
    stageId: "stage-07",
    title: "一擊擊敗萊莉",
    phase: "Victory slot 18",
    description: "萊莉只剩 1 點生命且位於妮雅身邊；其餘奇襲隊仍在場。",
    fixture: true,
  },
  {
    id: "stage-07-near-defeat",
    stageId: "stage-07",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-07-victory-ready",
    stageId: "stage-07",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "萊莉已離場，直接驗證無戰後劇情的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-07-cleared",
    stageId: "stage-07",
    title: "完成路由",
    phase: "Route to stage 8",
    description: "視為第 7 關已完成，直接進入「營地遭到偷襲」第 8 關關前劇情。",
    fixture: true,
  },
  {
    id: "stage-08-prebattle",
    stageId: "stage-08",
    title: "關前劇情",
    phase: "SAY/0021",
    description: "從本關最初狀態開始，保留 BK/7、BK/6、BK/8 三背景劇情。",
  },
  {
    id: "stage-08-opening",
    stageId: "stage-08",
    title: "開戰劇情",
    phase: "SAY/0156",
    description: "跳過關前劇情，直接查看固定戰場上的第 1 回合兩頁說明。",
  },
  {
    id: "stage-08-player",
    stageId: "stage-08",
    title: "玩家回合",
    phase: "Round 1",
    description: "八名我方單位全部由玩家操作，蘇蘭達擔任集團主將。",
  },
  {
    id: "stage-08-free-action",
    stageId: "stage-08",
    title: "自由行動",
    phase: "Free action",
    description: "發出自由行動命令，驗證八名玩家單位可主動交給共享專家 AI。",
    fixture: true,
  },
  {
    id: "stage-08-near-victory",
    stageId: "stage-08",
    title: "最後一名敵軍",
    phase: "Eliminate side 2",
    description: "其餘十名襲擊者已離場，最後一名敵軍只剩 1 點生命並位於蘇蘭達身邊。",
    fixture: true,
  },
  {
    id: "stage-08-near-defeat",
    stageId: "stage-08",
    title: "蘇蘭達近敗",
    phase: "Defeat setup",
    description: "蘇蘭達只剩 1 點生命，最近敵兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-08-victory-ready",
    stageId: "stage-08",
    title: "勝利對白",
    phase: "SAY/0157",
    description: "全部敵軍已離場，驗證 REMAKE-032 補播的蘇蘭達撤離對白與後續編號保存。",
    fixture: true,
  },
  {
    id: "stage-08-cleared",
    stageId: "stage-08",
    title: "完成路由",
    phase: "Route to stage 9",
    description: "視為第 8 關已完成，直接進入「找尋傳說中的飛船」第 9 關部署。",
    fixture: true,
  },
  {
    id: "stage-09-deployment",
    stageId: "stage-09",
    title: "死亡之谷部署",
    phase: "2/9 initial",
    description: "直接開啟正式部署；多莉與妮雅固定，十二名候選最多選七人。",
  },
  {
    id: "stage-09-opening",
    stageId: "stage-09",
    title: "開戰對白",
    phase: "SAY/0022",
    description: "九人編隊完成部署，直接查看多莉請求妮雅保護的五頁對白。",
  },
  {
    id: "stage-09-player",
    stageId: "stage-09",
    title: "玩家回合",
    phase: "Round 1",
    description: "九人編隊進入玩家階段；多莉依原版路線獨立引路，其餘八人由玩家控制。",
  },
  {
    id: "stage-09-near-route",
    stageId: "stage-09",
    title: "多莉一步登船",
    phase: "Behavior 12 / Victory 999",
    description: "多莉距谷頂一次獨立行動；結束玩家回合即可驗證安全終點與 SAY/0023。",
    fixture: true,
  },
  {
    id: "stage-09-near-elimination",
    stageId: "stage-09",
    title: "最後一名敵軍",
    phase: "Alternative victory",
    description: "其餘封鎖隊已離場，最後一名敵軍只剩 1 點生命並位於妮雅身邊。",
    fixture: true,
  },
  {
    id: "stage-09-near-defeat",
    stageId: "stage-09",
    title: "多莉近敗",
    phase: "Defeat setup",
    description: "多莉只剩 1 點生命，最近敵兵位於相鄰格，可驗證雙保護目標。",
    fixture: true,
  },
  {
    id: "stage-09-victory-ready",
    stageId: "stage-09",
    title: "勝利對白",
    phase: "SAY/0023",
    description: "以全滅替代條件直接觸發勝利，驗證多莉登船對白與編號保存。",
    fixture: true,
  },
  {
    id: "stage-09-cleared",
    stageId: "stage-09",
    title: "完成路由",
    phase: "Route to stage 11",
    description: "視為第 9 關已完成，直接進入「拯救蘇蘭達」固定戰場與 SAY/0024。",
    fixture: true,
  },
  {
    id: "stage-11-opening",
    stageId: "stage-11",
    title: "飛船抵達",
    phase: "SAY/0024–0026",
    description: "查看蘇蘭達整隊、妮雅放下繩梯與全軍登船的十三頁開場對白；結束後多莉才離開棋盤。",
  },
  {
    id: "stage-11-player",
    stageId: "stage-11",
    title: "玩家回合",
    phase: "Round 1",
    description: "多莉已留在飛船上，蘇蘭達與七名游騎兵全部由玩家控制。",
  },
  {
    id: "stage-11-near-route",
    stageId: "stage-11",
    title: "一步抵達登船區",
    phase: "Victory 999",
    description: "蘇蘭達距原版格號 0..279 登船區一步，可直接驗證護送勝利。",
    fixture: true,
  },
  {
    id: "stage-11-near-defeat",
    stageId: "stage-11",
    title: "蘇蘭達近敗",
    phase: "Defeat setup",
    description: "蘇蘭達只剩 1 點生命，初始飛馬追擊兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-11-victory-ready",
    stageId: "stage-11",
    title: "登船完成對白",
    phase: "SAY/0027",
    description: "蘇蘭達已進入登船區，直接驗證全員上船、出發對白與編號保存。",
    fixture: true,
  },
  {
    id: "stage-11-cleared",
    stageId: "stage-11",
    title: "完成路由",
    phase: "Route to stage 10",
    description: "視為拯救蘇蘭達已完成，直接進入「飛船上遭遇敵人」關前劇情。",
    fixture: true,
  },
  {
    id: "stage-10-prebattle",
    stageId: "stage-10",
    title: "關前劇情",
    phase: "SAY/0028",
    description: "查看飞船上讨论龙塔去向与追兵迫近的 15 页 BK/10 剧情。",
  },
  {
    id: "stage-10-deployment",
    stageId: "stage-10",
    title: "飛船甲板部署",
    phase: "1/13 initial",
    description: "直接開啟正式部署；妮雅固定，十九名候選最多選十二人。",
  },
  {
    id: "stage-10-player",
    stageId: "stage-10",
    title: "玩家回合",
    phase: "Round 1",
    description: "十三人完整編隊進入玩家階段，對抗五名飛馬／半龍追兵。",
  },
  {
    id: "stage-10-near-victory",
    stageId: "stage-10",
    title: "最後一名追兵",
    phase: "Eliminate side 2",
    description: "其餘四名追兵已離場，最後一名敵軍只剩 1 點生命並位於妮雅身邊。",
    fixture: true,
  },
  {
    id: "stage-10-near-defeat",
    stageId: "stage-10",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，克諾絲位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-10-victory-ready",
    stageId: "stage-10",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "全部追兵已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-10-cleared",
    stageId: "stage-10",
    title: "完成路由",
    phase: "Route to stage 12",
    description: "視為飛船追擊戰已完成，直接進入「落入沼澤」墜船關前劇情。",
    fixture: true,
  },
  {
    id: "stage-12-prebattle",
    stageId: "stage-12",
    title: "飛船墜落",
    phase: "SAY/0029",
    description: "查看怪物撞擊飛船、眾人墜入沼澤的 11 頁 BK/10–13 劇情。",
  },
  {
    id: "stage-12-deployment",
    stageId: "stage-12",
    title: "沼澤部署",
    phase: "1/9 initial",
    description: "直接開啟正式部署；妮雅固定，十九名候選最多選八人。",
  },
  {
    id: "stage-12-opening",
    stageId: "stage-12",
    title: "水戰士現身",
    phase: "SAY/0030",
    description: "完整九人部署後查看 BK/14 的沼澤著陸與水戰士現身對話。",
  },
  {
    id: "stage-12-player",
    stageId: "stage-12",
    title: "玩家回合",
    phase: "Round 1",
    description: "九人完整編隊進入玩家階段，對抗東側五個水戰士根單位。",
  },
  {
    id: "stage-12-split",
    stageId: "stage-12",
    title: "水戰士分裂",
    phase: "Shared-life split",
    description: "根槽 40 已受到一次普通近戰攻擊，展示一個共享生命的分裂身體。",
    fixture: true,
  },
  {
    id: "stage-12-near-victory",
    stageId: "stage-12",
    title: "最後一組水戰士",
    phase: "Eliminate side 2",
    description: "其餘四組已離場，最後一個水戰士根單位只剩 1 點生命並位於妮雅身邊。",
    fixture: true,
  },
  {
    id: "stage-12-near-defeat",
    stageId: "stage-12",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，水戰士位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-12-victory-ready",
    stageId: "stage-12",
    title: "收服水戰士",
    phase: "SAY/0031",
    description: "全部水戰士已離場，直接驗證葛蒂拉斯收服水戰士的勝利對話與編號保存。",
    fixture: true,
  },
  {
    id: "stage-12-cleared",
    stageId: "stage-12",
    title: "完成路由",
    phase: "Route to stage 13",
    description: "視為沼澤戰已完成，停在「龍塔外」內部第 13 關凍結邊界。",
    fixture: true,
  },
  {
    id: "stage-13-prebattle",
    stageId: "stage-13",
    title: "龍塔突擊會議",
    phase: "SAY/0032",
    description: "查看妮雅一行發現龍塔、決定派精銳小隊突擊的 10 頁 BK/15 劇情。",
  },
  {
    id: "stage-13-deployment",
    stageId: "stage-13",
    title: "龍塔外部署",
    phase: "1/12 initial",
    description: "直接開啟正式部署；妮雅固定，二十一名候選最多選十一人。",
  },
  {
    id: "stage-13-player",
    stageId: "stage-13",
    title: "玩家回合",
    phase: "Round 1",
    description: "十二人完整編隊進入玩家階段，對抗瑪西爾率領的九名龍塔守軍。",
  },
  {
    id: "stage-13-near-victory",
    stageId: "stage-13",
    title: "一擊擊敗瑪西爾",
    phase: "Leader victory 999",
    description: "瑪西爾只剩 1 點生命且位於妮雅身邊；其餘八名敵軍保留，用於驗證首領目標。",
    fixture: true,
  },
  {
    id: "stage-13-near-defeat",
    stageId: "stage-13",
    title: "妮雅近敗",
    phase: "Defeat setup",
    description: "妮雅只剩 1 點生命，敵方騎兵位於相鄰格。",
    fixture: true,
  },
  {
    id: "stage-13-victory-ready",
    stageId: "stage-13",
    title: "勝利準備",
    phase: "Victory feedback",
    description: "瑪西爾已離場，直接驗證無戰後 SAY 的普通勝利回饋與編號保存。",
    fixture: true,
  },
  {
    id: "stage-13-cleared",
    stageId: "stage-13",
    title: "完成路由",
    phase: "Route to stage 14",
    description: "視為龍塔外戰鬥已完成，停在「龍塔第一層」內部第 14 關凍結邊界。",
    fixture: true,
  },
] as const satisfies readonly DebugScenarioDefinition[];

export type DebugScenarioId = typeof DEBUG_SCENARIOS[number]["id"];

export function isDebugScenarioId(value: unknown): value is DebugScenarioId {
  return typeof value === "string"
    && DEBUG_SCENARIOS.some(({ id }) => id === value);
}

export function debugScenarioUrl(
  id: DebugScenarioId,
  difficulty: Difficulty,
  rosterSourceId?: DebugRosterSourceId,
  perStageGrowth?: number,
): string {
  const parameters = new URLSearchParams({ debugScenario: id, difficulty: String(difficulty) });
  if (rosterSourceId) parameters.set("roster", rosterSourceId);
  if (perStageGrowth !== undefined) {
    parameters.set("growth", String(perStageGrowth));
  }
  return `/?${parameters.toString()}`;
}
