// Generated by scripts/generate-ai-technique-dialogue.mjs from native AI evidence.
// Do not hand-edit.
export interface NativeAiTechniqueDialogueRecord {
  readonly nativeCode: string;
  readonly presentationGroup: number;
  readonly selector: number;
  readonly address: `DS:${string}`;
  readonly text: string;
}

export const NATIVE_AI_TECHNIQUE_DIALOGUE_GROUPS = [
  {
    "presentationGroup": 10,
    "selector": 10,
    "pointerEntry": "DS:84CF",
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  {
    "presentationGroup": 11,
    "selector": 11,
    "pointerEntry": "DS:84D1",
    "address": "DS:85DA",
    "text": "看我的雷電魔法."
  },
  {
    "presentationGroup": 12,
    "selector": 12,
    "pointerEntry": "DS:84D3",
    "address": "DS:85EA",
    "text": "看我的冰魔法."
  },
  {
    "presentationGroup": 13,
    "selector": 13,
    "pointerEntry": "DS:84D5",
    "address": "DS:85F8",
    "text": "看我的巨龍."
  },
  {
    "presentationGroup": 14,
    "selector": 14,
    "pointerEntry": "DS:84D7",
    "address": "DS:8604",
    "text": "生命全."
  },
  {
    "presentationGroup": 15,
    "selector": 15,
    "pointerEntry": "DS:84D9",
    "address": "DS:860C",
    "text": "生命單."
  },
  {
    "presentationGroup": 16,
    "selector": 16,
    "pointerEntry": "DS:84DB",
    "address": "DS:8614",
    "text": "防禦提昇."
  },
  {
    "presentationGroup": 17,
    "selector": 17,
    "pointerEntry": "DS:84DD",
    "address": "DS:861E",
    "text": "功擊提昇."
  },
  {
    "presentationGroup": 18,
    "selector": 18,
    "pointerEntry": "DS:84DF",
    "address": "DS:8628",
    "text": "防禦降低."
  },
  {
    "presentationGroup": 19,
    "selector": 19,
    "pointerEntry": "DS:84E1",
    "address": "DS:8632",
    "text": "功擊降低."
  },
  {
    "presentationGroup": 20,
    "selector": 20,
    "pointerEntry": "DS:84E3",
    "address": "DS:863C",
    "text": "中毒."
  },
  {
    "presentationGroup": 21,
    "selector": 21,
    "pointerEntry": "DS:84E5",
    "address": "DS:8642",
    "text": "禁咒."
  },
  {
    "presentationGroup": 22,
    "selector": 22,
    "pointerEntry": "DS:84E7",
    "address": "DS:8648",
    "text": "混亂."
  },
  {
    "presentationGroup": 23,
    "selector": 23,
    "pointerEntry": "DS:84E9",
    "address": "DS:864E",
    "text": "破邪."
  }
] as const;

export const NATIVE_AI_TECHNIQUE_DIALOGUE_BY_CODE: Readonly<Record<string, NativeAiTechniqueDialogueRecord>> = {
  "1L": {
    "nativeCode": "1L",
    "presentationGroup": 11,
    "selector": 11,
    "address": "DS:85DA",
    "text": "看我的雷電魔法."
  },
  "2L": {
    "nativeCode": "2L",
    "presentationGroup": 11,
    "selector": 11,
    "address": "DS:85DA",
    "text": "看我的雷電魔法."
  },
  "3L": {
    "nativeCode": "3L",
    "presentationGroup": 11,
    "selector": 11,
    "address": "DS:85DA",
    "text": "看我的雷電魔法."
  },
  "4L": {
    "nativeCode": "4L",
    "presentationGroup": 11,
    "selector": 11,
    "address": "DS:85DA",
    "text": "看我的雷電魔法."
  },
  "1F": {
    "nativeCode": "1F",
    "presentationGroup": 10,
    "selector": 10,
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  "2F": {
    "nativeCode": "2F",
    "presentationGroup": 10,
    "selector": 10,
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  "3F": {
    "nativeCode": "3F",
    "presentationGroup": 10,
    "selector": 10,
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  "4F": {
    "nativeCode": "4F",
    "presentationGroup": 10,
    "selector": 10,
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  "1V": {
    "nativeCode": "1V",
    "presentationGroup": 10,
    "selector": 10,
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  "2V": {
    "nativeCode": "2V",
    "presentationGroup": 10,
    "selector": 10,
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  "3V": {
    "nativeCode": "3V",
    "presentationGroup": 10,
    "selector": 10,
    "address": "DS:85CA",
    "text": "看我的火球魔法."
  },
  "1C": {
    "nativeCode": "1C",
    "presentationGroup": 12,
    "selector": 12,
    "address": "DS:85EA",
    "text": "看我的冰魔法."
  },
  "2C": {
    "nativeCode": "2C",
    "presentationGroup": 12,
    "selector": 12,
    "address": "DS:85EA",
    "text": "看我的冰魔法."
  },
  "3C": {
    "nativeCode": "3C",
    "presentationGroup": 12,
    "selector": 12,
    "address": "DS:85EA",
    "text": "看我的冰魔法."
  },
  "4C": {
    "nativeCode": "4C",
    "presentationGroup": 12,
    "selector": 12,
    "address": "DS:85EA",
    "text": "看我的冰魔法."
  },
  "1D": {
    "nativeCode": "1D",
    "presentationGroup": 13,
    "selector": 13,
    "address": "DS:85F8",
    "text": "看我的巨龍."
  },
  "2D": {
    "nativeCode": "2D",
    "presentationGroup": 13,
    "selector": 13,
    "address": "DS:85F8",
    "text": "看我的巨龍."
  },
  "3D": {
    "nativeCode": "3D",
    "presentationGroup": 13,
    "selector": 13,
    "address": "DS:85F8",
    "text": "看我的巨龍."
  },
  "1I": {
    "nativeCode": "1I",
    "presentationGroup": 14,
    "selector": 14,
    "address": "DS:8604",
    "text": "生命全."
  },
  "2I": {
    "nativeCode": "2I",
    "presentationGroup": 14,
    "selector": 14,
    "address": "DS:8604",
    "text": "生命全."
  },
  "3I": {
    "nativeCode": "3I",
    "presentationGroup": 14,
    "selector": 14,
    "address": "DS:8604",
    "text": "生命全."
  },
  "1H": {
    "nativeCode": "1H",
    "presentationGroup": 15,
    "selector": 15,
    "address": "DS:860C",
    "text": "生命單."
  },
  "2H": {
    "nativeCode": "2H",
    "presentationGroup": 15,
    "selector": 15,
    "address": "DS:860C",
    "text": "生命單."
  },
  "3H": {
    "nativeCode": "3H",
    "presentationGroup": 15,
    "selector": 15,
    "address": "DS:860C",
    "text": "生命單."
  },
  "AD": {
    "nativeCode": "AD",
    "presentationGroup": 16,
    "selector": 16,
    "address": "DS:8614",
    "text": "防禦提昇."
  },
  "AA": {
    "nativeCode": "AA",
    "presentationGroup": 17,
    "selector": 17,
    "address": "DS:861E",
    "text": "功擊提昇."
  },
  "SD": {
    "nativeCode": "SD",
    "presentationGroup": 18,
    "selector": 18,
    "address": "DS:8628",
    "text": "防禦降低."
  },
  "SA": {
    "nativeCode": "SA",
    "presentationGroup": 19,
    "selector": 19,
    "address": "DS:8632",
    "text": "功擊降低."
  },
  "IP": {
    "nativeCode": "IP",
    "presentationGroup": 20,
    "selector": 20,
    "address": "DS:863C",
    "text": "中毒."
  },
  "SN": {
    "nativeCode": "SN",
    "presentationGroup": 21,
    "selector": 21,
    "address": "DS:8642",
    "text": "禁咒."
  },
  "LA": {
    "nativeCode": "LA",
    "presentationGroup": 22,
    "selector": 22,
    "address": "DS:8648",
    "text": "混亂."
  },
  "TR": {
    "nativeCode": "TR",
    "presentationGroup": 23,
    "selector": 23,
    "address": "DS:864E",
    "text": "破邪."
  },
  "WD": {
    "nativeCode": "WD",
    "presentationGroup": 11,
    "selector": 11,
    "address": "DS:85DA",
    "text": "看我的雷電魔法."
  }
};

/**
 * Contextual line `DS:84BB[1Ch]`. `0000:66F4` plays it with the clicked unit's
 * portrait before handing a confused player unit to the single-unit AI entry,
 * and it calls `0000:C97E` directly, so the ＡＩ對話 switch never gates it.
 */
export const NATIVE_CONFUSED_ACTOR_DIALOGUE = {
  "selector": 28,
  "pointerEntry": "DS:84F3",
  "address": "DS:86AB",
  "text": "我的頭好昏，無法思考．"
} as const;
