// Generated by scripts/generate-battle-sprite-atlases.mjs.
// Do not hand-edit.
export const BATTLE_SPRITE_ATLASES = [
  {
    "id": "map-combat",
    "textureKey": "battle-sprite-map-combat",
    "image": "/assets/original/battle-sprite-atlases/map-combat.png",
    "data": "/assets/original/battle-sprite-atlases/map-combat.json",
    "width": 1010,
    "height": 94,
    "decodedBytes": 379760,
    "frameCount": 46
  },
  {
    "id": "turn-transition",
    "textureKey": "battle-sprite-turn-transition",
    "image": "/assets/original/battle-sprite-atlases/turn-transition.png",
    "data": "/assets/original/battle-sprite-atlases/turn-transition.json",
    "width": 668,
    "height": 103,
    "decodedBytes": 275216,
    "frameCount": 9
  },
  {
    "id": "stage4-force-field-pulse",
    "textureKey": "battle-sprite-stage4-force-field-pulse",
    "image": "/assets/original/battle-sprite-atlases/stage4-force-field-pulse.png",
    "data": "/assets/original/battle-sprite-atlases/stage4-force-field-pulse.json",
    "width": 540,
    "height": 48,
    "decodedBytes": 103680,
    "frameCount": 13
  },
  {
    "id": "stage26-column-push",
    "textureKey": "battle-sprite-stage26-column-push",
    "image": "/assets/original/battle-sprite-atlases/stage26-column-push.png",
    "data": "/assets/original/battle-sprite-atlases/stage26-column-push.json",
    "width": 1010,
    "height": 94,
    "decodedBytes": 379760,
    "frameCount": 41
  }
] as const;

export const BATTLE_SPRITE_ATLAS_FRAMES = {
  "/assets/original/map-combat/death/00.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/00"
  },
  "/assets/original/map-combat/death/01.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/01"
  },
  "/assets/original/map-combat/death/02.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/02"
  },
  "/assets/original/map-combat/death/03.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/03"
  },
  "/assets/original/map-combat/death/04.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/04"
  },
  "/assets/original/map-combat/death/05.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/05"
  },
  "/assets/original/map-combat/death/06.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/06"
  },
  "/assets/original/map-combat/death/07.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/07"
  },
  "/assets/original/map-combat/death/08.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/08"
  },
  "/assets/original/map-combat/death/09.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/09"
  },
  "/assets/original/map-combat/death/10.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/10"
  },
  "/assets/original/map-combat/death/11.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/11"
  },
  "/assets/original/map-combat/death/12.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/12"
  },
  "/assets/original/map-combat/death/13.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/13"
  },
  "/assets/original/map-combat/death/14.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/14"
  },
  "/assets/original/map-combat/death/15.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/15"
  },
  "/assets/original/map-combat/death/16.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/16"
  },
  "/assets/original/map-combat/death/17.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/17"
  },
  "/assets/original/map-combat/death/18.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/18"
  },
  "/assets/original/map-combat/death/19.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/19"
  },
  "/assets/original/map-combat/death/20.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/20"
  },
  "/assets/original/map-combat/death/21.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/21"
  },
  "/assets/original/map-combat/death/22.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/22"
  },
  "/assets/original/map-combat/death/23.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/23"
  },
  "/assets/original/map-combat/death/24.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/24"
  },
  "/assets/original/map-combat/death/25.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/25"
  },
  "/assets/original/map-combat/death/26.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/26"
  },
  "/assets/original/map-combat/death/27.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/27"
  },
  "/assets/original/map-combat/death/28.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/28"
  },
  "/assets/original/map-combat/death/29.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/29"
  },
  "/assets/original/map-combat/death/30.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/30"
  },
  "/assets/original/map-combat/death/31.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/31"
  },
  "/assets/original/map-combat/death/32.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/32"
  },
  "/assets/original/map-combat/death/33.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/33"
  },
  "/assets/original/map-combat/death/34.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/34"
  },
  "/assets/original/map-combat/death/35.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/35"
  },
  "/assets/original/map-combat/death/36.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/36"
  },
  "/assets/original/map-combat/death/37.png": {
    "atlas": "map-combat",
    "frame": "map-combat/death/37"
  },
  "/assets/original/map-combat/hit/00.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/00"
  },
  "/assets/original/map-combat/hit/01.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/01"
  },
  "/assets/original/map-combat/hit/02.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/02"
  },
  "/assets/original/map-combat/hit/03.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/03"
  },
  "/assets/original/map-combat/hit/04.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/04"
  },
  "/assets/original/map-combat/hit/05.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/05"
  },
  "/assets/original/map-combat/hit/06.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/06"
  },
  "/assets/original/map-combat/hit/07.png": {
    "atlas": "map-combat",
    "frame": "map-combat/hit/07"
  },
  "/assets/original/turn-transition-player.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/player"
  },
  "/assets/original/turn-transition-enemy.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/enemy"
  },
  "/assets/original/turn-transition-shadow.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/shadow"
  },
  "/assets/original/turn-transition-dust-00.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/dust-00"
  },
  "/assets/original/turn-transition-dust-01.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/dust-01"
  },
  "/assets/original/turn-transition-dust-02.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/dust-02"
  },
  "/assets/original/turn-transition-dust-03.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/dust-03"
  },
  "/assets/original/turn-transition-dust-04.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/dust-04"
  },
  "/assets/original/turn-transition-dust-05.png": {
    "atlas": "turn-transition",
    "frame": "turn-transition/dust-05"
  },
  "/assets/original/stage4-force-field-pulse/00.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/00"
  },
  "/assets/original/stage4-force-field-pulse/01.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/01"
  },
  "/assets/original/stage4-force-field-pulse/02.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/02"
  },
  "/assets/original/stage4-force-field-pulse/03.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/03"
  },
  "/assets/original/stage4-force-field-pulse/04.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/04"
  },
  "/assets/original/stage4-force-field-pulse/05.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/05"
  },
  "/assets/original/stage4-force-field-pulse/06.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/06"
  },
  "/assets/original/stage4-force-field-pulse/07.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/07"
  },
  "/assets/original/stage4-force-field-pulse/08.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/08"
  },
  "/assets/original/stage4-force-field-pulse/09.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/09"
  },
  "/assets/original/stage4-force-field-pulse/10.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/10"
  },
  "/assets/original/stage4-force-field-pulse/11.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/11"
  },
  "/assets/original/stage4-force-field-pulse/12.png": {
    "atlas": "stage4-force-field-pulse",
    "frame": "stage4-force-field-pulse/12"
  },
  "/assets/original/stage26-column-push/phase1/00.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/00"
  },
  "/assets/original/stage26-column-push/phase1/01.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/01"
  },
  "/assets/original/stage26-column-push/phase1/02.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/02"
  },
  "/assets/original/stage26-column-push/phase1/03.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/03"
  },
  "/assets/original/stage26-column-push/phase1/04.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/04"
  },
  "/assets/original/stage26-column-push/phase1/05.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/05"
  },
  "/assets/original/stage26-column-push/phase1/06.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/06"
  },
  "/assets/original/stage26-column-push/phase1/07.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/07"
  },
  "/assets/original/stage26-column-push/phase1/08.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/08"
  },
  "/assets/original/stage26-column-push/phase1/09.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/09"
  },
  "/assets/original/stage26-column-push/phase1/10.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/10"
  },
  "/assets/original/stage26-column-push/phase1/11.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/11"
  },
  "/assets/original/stage26-column-push/phase1/12.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/12"
  },
  "/assets/original/stage26-column-push/phase1/13.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/13"
  },
  "/assets/original/stage26-column-push/phase1/14.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/14"
  },
  "/assets/original/stage26-column-push/phase1/15.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/15"
  },
  "/assets/original/stage26-column-push/phase1/16.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/16"
  },
  "/assets/original/stage26-column-push/phase1/17.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/17"
  },
  "/assets/original/stage26-column-push/phase1/18.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/18"
  },
  "/assets/original/stage26-column-push/phase1/19.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/19"
  },
  "/assets/original/stage26-column-push/phase1/20.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/20"
  },
  "/assets/original/stage26-column-push/phase1/21.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/21"
  },
  "/assets/original/stage26-column-push/phase1/22.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/22"
  },
  "/assets/original/stage26-column-push/phase1/23.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/23"
  },
  "/assets/original/stage26-column-push/phase1/24.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/24"
  },
  "/assets/original/stage26-column-push/phase1/25.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/25"
  },
  "/assets/original/stage26-column-push/phase1/26.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/26"
  },
  "/assets/original/stage26-column-push/phase1/27.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/27"
  },
  "/assets/original/stage26-column-push/phase1/28.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/28"
  },
  "/assets/original/stage26-column-push/phase1/29.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase1/29"
  },
  "/assets/original/stage26-column-push/phase2/00.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/00"
  },
  "/assets/original/stage26-column-push/phase2/01.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/01"
  },
  "/assets/original/stage26-column-push/phase2/02.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/02"
  },
  "/assets/original/stage26-column-push/phase2/03.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/03"
  },
  "/assets/original/stage26-column-push/phase2/04.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/04"
  },
  "/assets/original/stage26-column-push/phase2/05.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/05"
  },
  "/assets/original/stage26-column-push/phase2/06.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/06"
  },
  "/assets/original/stage26-column-push/phase2/07.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/07"
  },
  "/assets/original/stage26-column-push/phase2/08.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/08"
  },
  "/assets/original/stage26-column-push/phase2/09.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/09"
  },
  "/assets/original/stage26-column-push/phase2/10.png": {
    "atlas": "stage26-column-push",
    "frame": "stage26-column-push/phase2/10"
  }
} as const;
