// Generated by scripts/generate-map-action-atlases.mjs.
// Do not hand-edit.
export const MAP_ACTION_ATLAS_IDS = ["shoot","fire-1","fire-2","fire-3","fire-4","heal-1","heal-2","heal-3","lightning-1","lightning-2","lightning-3","lightning-4","ice-1","recovery-1","attack-up","defense-up","poison","confusion","attack-down","defense-down","spell-seal","dispel","stomp-1","stomp-2","stomp-3","wd"] as const;

export const MAP_ACTION_ATLASES = [
  {
    "id": "shoot",
    "textureKey": "map-action-shoot",
    "image": "/assets/original/map-action-atlases/shoot.png",
    "data": "/assets/original/map-action-atlases/shoot.json"
  },
  {
    "id": "fire-1",
    "textureKey": "map-action-fire-1",
    "image": "/assets/original/map-action-atlases/fire-1.png",
    "data": "/assets/original/map-action-atlases/fire-1.json"
  },
  {
    "id": "fire-2",
    "textureKey": "map-action-fire-2",
    "image": "/assets/original/map-action-atlases/fire-2.png",
    "data": "/assets/original/map-action-atlases/fire-2.json"
  },
  {
    "id": "fire-3",
    "textureKey": "map-action-fire-3",
    "image": "/assets/original/map-action-atlases/fire-3.png",
    "data": "/assets/original/map-action-atlases/fire-3.json"
  },
  {
    "id": "fire-4",
    "textureKey": "map-action-fire-4",
    "image": "/assets/original/map-action-atlases/fire-4.png",
    "data": "/assets/original/map-action-atlases/fire-4.json"
  },
  {
    "id": "heal-1",
    "textureKey": "map-action-heal-1",
    "image": "/assets/original/map-action-atlases/heal-1.png",
    "data": "/assets/original/map-action-atlases/heal-1.json"
  },
  {
    "id": "heal-2",
    "textureKey": "map-action-heal-2",
    "image": "/assets/original/map-action-atlases/heal-2.png",
    "data": "/assets/original/map-action-atlases/heal-2.json"
  },
  {
    "id": "heal-3",
    "textureKey": "map-action-heal-3",
    "image": "/assets/original/map-action-atlases/heal-3.png",
    "data": "/assets/original/map-action-atlases/heal-3.json"
  },
  {
    "id": "lightning-1",
    "textureKey": "map-action-lightning-1",
    "image": "/assets/original/map-action-atlases/lightning-1.png",
    "data": "/assets/original/map-action-atlases/lightning-1.json"
  },
  {
    "id": "lightning-2",
    "textureKey": "map-action-lightning-2",
    "image": "/assets/original/map-action-atlases/lightning-2.png",
    "data": "/assets/original/map-action-atlases/lightning-2.json"
  },
  {
    "id": "lightning-3",
    "textureKey": "map-action-lightning-3",
    "image": "/assets/original/map-action-atlases/lightning-3.png",
    "data": "/assets/original/map-action-atlases/lightning-3.json"
  },
  {
    "id": "lightning-4",
    "textureKey": "map-action-lightning-4",
    "image": "/assets/original/map-action-atlases/lightning-4.png",
    "data": "/assets/original/map-action-atlases/lightning-4.json"
  },
  {
    "id": "ice-1",
    "textureKey": "map-action-ice-1",
    "image": "/assets/original/map-action-atlases/ice-1.png",
    "data": "/assets/original/map-action-atlases/ice-1.json"
  },
  {
    "id": "recovery-1",
    "textureKey": "map-action-recovery-1",
    "image": "/assets/original/map-action-atlases/recovery-1.png",
    "data": "/assets/original/map-action-atlases/recovery-1.json"
  },
  {
    "id": "attack-up",
    "textureKey": "map-action-attack-up",
    "image": "/assets/original/map-action-atlases/attack-up.png",
    "data": "/assets/original/map-action-atlases/attack-up.json"
  },
  {
    "id": "defense-up",
    "textureKey": "map-action-defense-up",
    "image": "/assets/original/map-action-atlases/defense-up.png",
    "data": "/assets/original/map-action-atlases/defense-up.json"
  },
  {
    "id": "poison",
    "textureKey": "map-action-poison",
    "image": "/assets/original/map-action-atlases/poison.png",
    "data": "/assets/original/map-action-atlases/poison.json"
  },
  {
    "id": "confusion",
    "textureKey": "map-action-confusion",
    "image": "/assets/original/map-action-atlases/confusion.png",
    "data": "/assets/original/map-action-atlases/confusion.json"
  },
  {
    "id": "attack-down",
    "textureKey": "map-action-attack-down",
    "image": "/assets/original/map-action-atlases/attack-down.png",
    "data": "/assets/original/map-action-atlases/attack-down.json"
  },
  {
    "id": "defense-down",
    "textureKey": "map-action-defense-down",
    "image": "/assets/original/map-action-atlases/defense-down.png",
    "data": "/assets/original/map-action-atlases/defense-down.json"
  },
  {
    "id": "spell-seal",
    "textureKey": "map-action-spell-seal",
    "image": "/assets/original/map-action-atlases/spell-seal.png",
    "data": "/assets/original/map-action-atlases/spell-seal.json"
  },
  {
    "id": "dispel",
    "textureKey": "map-action-dispel",
    "image": "/assets/original/map-action-atlases/dispel.png",
    "data": "/assets/original/map-action-atlases/dispel.json"
  },
  {
    "id": "stomp-1",
    "textureKey": "map-action-stomp-1",
    "image": "/assets/original/map-action-atlases/stomp-1.png",
    "data": "/assets/original/map-action-atlases/stomp-1.json"
  },
  {
    "id": "stomp-2",
    "textureKey": "map-action-stomp-2",
    "image": "/assets/original/map-action-atlases/stomp-2.png",
    "data": "/assets/original/map-action-atlases/stomp-2.json"
  },
  {
    "id": "stomp-3",
    "textureKey": "map-action-stomp-3",
    "image": "/assets/original/map-action-atlases/stomp-3.png",
    "data": "/assets/original/map-action-atlases/stomp-3.json"
  },
  {
    "id": "wd",
    "textureKey": "map-action-wd",
    "image": "/assets/original/map-action-atlases/wd.png",
    "data": "/assets/original/map-action-atlases/wd.json"
  }
] as const;
