// Generated by scripts/generate-native-font.mjs from module-29 battle-text evidence.
// Do not hand-edit: regenerate with `pnpm content:font` after the evidence pipeline changes.

export const NATIVE_FONT_IDENTITY = "native-font/evidence-602513cdec9e96efff44faa049f3ad25b70f0a663277186577f9bd66c46bfb6a";
export const NATIVE_FONT_SOURCES = [{"id":"battle-text","path":"reverse/parsed/native/battle-text.json","sha256":"f5daa327cd26f65b054e9b6677ce28668a9ed41eab715f126ab8a40063154f79","bytes":24287},{"id":"battle-text-font","path":"reverse/parsed/native/battle-text-font.json","sha256":"892b0d338fd613fa8ba2ca9156bf0622a71c466c7cb37573f62c0b9fbef545ac","bytes":69195},{"id":"hud-presentations","path":"reverse/parsed/native/hud-presentations.json","sha256":"295840ec414082a213edbc00de7eb033d2da686e8cdbad85a5d37c4b86f92f63","bytes":41497},{"id":"bios-font","path":"reverse/dumps/bios-font-8x8.bin","sha256":"30458156768e070bc34ec72ed3485f002620da4619e4b4bab956779249aca363","bytes":2048}] as const;

/**
 * One atlas on a 16x16 cell grid. Cells `0..fullWidthCount-1` are the merged
 * original 16x15 glyphs; the remaining cells are ASCII `0x20..0x7F` from the
 * BIOS 8x8 ROM font with every row doubled, 8 pixels wide.
 */
export const NATIVE_FONT = {
  src: "/assets/original/native-font.png",
  cellWidth: 16,
  cellHeight: 16,
  columns: 16,
  fullWidthCount: 1253,
  fullWidthRows: 15,
  halfWidthBase: 1253,
  halfWidthFirstCode: 32,
  halfWidthCount: 96,
  halfWidthWidth: 8,
} as const;

/** Atlas order for the full-width cells: index `n` is code point `n` here. */
export const NATIVE_FONT_CHARACTERS = "　，、。．：？！【】「」『』＊～／│┐┘０１２３４５６７８９ⅠⅡⅢＡＢＣＩ一丁九了二人入八刀力十又三下上久也亡口土士大女子小山工己已弓才不中之予井五什仇仍今介內六公分切勾勿化升友及反天太少引心手支文斗方日月木止比水火片王世且主乎以付他代令充出加功包半卡占去可右召司叫另只史四外失它尼巨左布平必打本未正民永汀瓦甘生用由甲白目石示立丟交伙伊休伏件任份企光先全共再冰危吉同各向名合吃因回地在多夷妄好她如存宇守安尖年式忙成托收早有朵次此死灰米老考而耳自至色艾行西位住伴何估佐佔似但作你低佈克免兵冷別利劫助即吞否吧呃告吸吵吼呀困均妙妖妥完局巫希序弄役忘快我抗技把找批投抓改攻更束村杖杉步求沙決沒牠狂男皂私究見言谷走足身迅邪那里防阱並事些亞享依使來併佩兒兩其典刻到制卓卷取受呵咕咒呼和呢周命固坡夜奉奇妹妮姆始姓姊妳定官宜居幸底弩往彼忠忽念怪怕性或房所拉招披拍抵抱放斧於易明昇服東果林板枉欣注沼法油況沿治炎爭物狀疚的直知空者股肩肯芳芙花虎初表迎返近長門阿阻青非亮信侵便保侶係冒冑前則勇卻厚叛哀咦哇哈型城姿室封屋帝度建很待律後怒思急怎恢拜按拼持指拯挑政故施既是某架柯查段毒流活派洛洩為炸甚界相看研祈穿突紅美耶背苦若英要計負赴軍迫重降面音飛首倍倩值倒們個候修冤剛原哼唔唉哪哦埋套娜姬害家宮容射展峽峰差師庫座弱徒徑恭息悔扇拿挾挺挽效料旁時書根格氣泰消海涉烈特留病疲真眠破神祝秘窄站笑索純級納翅耗耽脆能草茵茱衰記討訊託訓豈起送退逃追配釘閃陣除隻馬骨高鬥鬼乾假做偷務動匿參曼商啦啊問唸圈國堅堆基執夠宿密將崇常帶張強得從悉您情惜控捲探接措掉推授掀救教敗啟斬族晚晨望梯桿桶棄梅條欲殺淡淺清混淚深淨牽猛率球理現產略畢異疏盛眾眼祥祭移第統細累終習脫船莎莽莊莉處蛋術被袍許設責軟這通連速造途部都野閉陸陰陷雪章竟頂麻傢備最創剩勞勝喂喪喔單圍堪場堤報堡富尋就嵐幾廊復惡惶插提揮援換揚散斯普晶景智曾替期朝棕棟森欺欽游渡測渾焦焰無然牌琪琳琴畫番痛登發硬稍程等策筆答結絕絲給肅舒著萊菲裂視訴象費貿越趁距跋跑跌軸辜進量開間隊階陽雅雄集雲項順須黑亂傳僅傷剷勢嗎嗯嗚園圓塔塊奧幹愚意感想愛搞搜損搖新暗會業楚極概毀殿滅準煙煩照煦煌當盟睛睜碰碑禁萬經綁置罩罪署群聖腳蒂落葛號補裝裡解該詳試誇誠話詭資跟路跳躲較載運遊道達逼遇過隔雷電預頓馴僧像厭嘛嘉嘍團圖塵境墓夥夢寧實寢察對徹態慢摔撤摧榮歉滿漆漸漫煽爾獄瑪疑瘋盡監磁碟碧種稱端管算精緊維聚膀與蒙蜜蝕語認誓誤說誘趕輔輕遠酷銀隙障需領麼齊劍厲嘻嘿嘴噗增寬層廢廝廣影德慶慮慾憤摩撞撐敵數暫暴樣樁標樂歐潔熟確碼箭範練緣緩罷蓬衛衝談請調誰論賦賭趟趣踏輝遭銳震靠鞏餘駐鬧魯儘凝器壇學導戰擅擁擋據擄擇操擔整曉橫樹橋機歷濃澤激燒獨瞞磚禦糕興艘融親謀諾蹂輸辨辦選遲醒錯鋼錄隨險雕靜頭龍儲嚎嚇壓幫應懂戲擊營牆療瞧禧糟績總縱繁聲聰聯聳臉舉薄蕾謊謝避還鍵鍊鍛隱雖顆鮮點黛叢擺斷歸璧癒禮簡職藏藍藉轉闖離雜雙題騎鬆壞龐懷爆獸礙禱穩繩羅識邊關難類顛騙麗嚴攔繼蘇覺觸議贏釋騷囂欄殲纏續蘭蠢護鐵霸露響顧魔囉權歡籠聾聽襲讀變顯驗體讓蠻觀釁躪呦褔鎧裏";

/** The gameplay VGA DAC entries every native battle colour index refers to. */
export const NATIVE_GAMEPLAY_PALETTE = ["#000000","#5d4131","#a27551","#e78a45","#ffbe69","#ffdbaa","#f79e9e","#baaa9a","#0000a6","#4d8aff","#ba61ff","#ef2024","#288200","#aee728","#ffdf10","#ffffff"] as const;

/** 0000:EA04 cursor rules; every advance is in native 640x350 pixels. */
export const NATIVE_TEXT = {
  terminators: ["$","\r","\u0000"],
  lineFeed: {"character":"|","resetsToStartX":true,"deltaY":20},
  advances: {"fullWidth":16,"halfWidth":9,"halfWidthCompact":8,"space":8,"tab":72},
  outline: {"fullWidth":{"function":"0000:ECCC","maskRows":17,"dilationRowOffsets":[0,1,2]},"halfWidth":{"function":"0000:ED03","maskRows":16,"dilationRowOffsets":[0,2]},"passes":[{"dx":0,"dy":0},{"dx":2,"dy":0}],"inkOffset":{"dx":1,"dy":1},"compactHalo":{"mode":"compact","colorIndex":0,"passes":[{"dx":-1,"dy":0},{"dx":3,"dy":0},{"dx":0,"dy":-1},{"dx":0,"dy":1}]}},
  colors: {"inkVariable":"DS:F93C","outlineVariable":"DS:F93E","battleInkIndex":15,"battleOutlineIndex":0},
  numericFieldCharacters: 5,
  identityFieldBytes: 8,
} as const;

/** 0000:8B2B, 0000:8C30, 0000:88E4 and 0000:4F41 origins, in native pixels. */
export const NATIVE_TEXT_ORIGINS = {
  occupation: {"x":484,"y":124},
  separator: {"x":552,"y":124},
  unitName: {"x":564,"y":124},
  round: {"x":516,"y":327},
  stageLabel: {"x":120,"y":333},
} as const;

/**
 * DS:5E64..DS:5EA2 templates and their 0000:8C30 origins. Each `00000` run is
 * a five-character numeric field, so the row is one native string rather than a
 * label column plus a right-aligned value column.
 */
export const NATIVE_STAT_ROWS = [
  {
    "id": "life",
    "template": "生命00000/00000 ",
    "x": 488,
    "y": 154
  },
  {
    "id": "attack",
    "template": "攻擊00000/00000 ",
    "x": 488,
    "y": 175
  },
  {
    "id": "defense",
    "template": "防禦00000/00000 ",
    "x": 488,
    "y": 196
  },
  {
    "id": "levelGrowthRow",
    "template": "等級00000 ",
    "x": 488,
    "y": 217
  },
  {
    "id": "experience",
    "template": "經驗00000/00000 ",
    "x": 488,
    "y": 238
  }
] as const;

/** Packed status counter origins; active statuses fill them in scan order. */
export const NATIVE_STATUS_COUNTERS = [{"x":478,"y":279},{"x":516,"y":279},{"x":554,"y":279},{"x":592,"y":279},{"x":478,"y":309},{"x":516,"y":309},{"x":554,"y":309},{"x":592,"y":309}] as const;

export const NATIVE_IDENTITY_SEPARATOR = "／";

/** DS:600B with its three converted digits still to be substituted. */
export const NATIVE_ROUND_TEMPLATE = "第  10  回合";
export const NATIVE_ROUND_DIGIT_INDICES = [2,3,4] as const;

/** DS:3051 and DS:305B, drawn before the A/0 bottom chrome covers both ends. */
export const NATIVE_STAGE_LABEL_BAR = [{"id":"labelBarOuter","address":"DS:3051","x":0,"y":332,"width":480,"height":18,"colorIndex":14},{"id":"labelBarInner","address":"DS:305B","x":80,"y":333,"width":320,"height":16,"colorIndex":1}] as const;

/** Visible label text to the padded SAY record the original ran the cursor on. */
export const NATIVE_STAGE_LABEL_PADDING: Readonly<Record<string, string>> = {
  "瑪姬的墓園": "      瑪姬的墓園    ",
  "瓦爾克麗宮": "\t瓦爾克麗宮\t",
  "騎士城堡前": "\t騎士城堡前\t",
  "攻打騎士堡": "\t攻打騎士堡\t",
  "救援友軍": "\t救援友軍\t",
  "通過力場": "\t通過力場\t",
  "遭遇丁塔琪": "\t遭遇丁塔琪\t",
  "來到異世界": "\t來到異世界\t",
  "營地遭到偷襲": "\t營地遭到偷襲\t",
  "營地遭到偷襲 ２": "\t營地遭到偷襲 ２ ",
  "找尋傳說中的飛船": "      找尋傳說中的飛船",
  "飛船上遭遇敵人": "\t飛船上遭遇敵人\t",
  "拯救蘇蘭達": "\t拯救蘇蘭達\t",
  "落入沼澤": "\t  落入沼澤\t  ",
  "龍塔外": "\t龍塔外\t    ",
  "龍塔第一層": "\t龍塔第一層\t",
  "龍塔第二層": "\t龍塔第二層\t",
  "龍塔第三層": "\t龍塔第三層\t",
  "龍塔第四層": "\t龍塔第四層\t",
  "龍塔第五層": "\t龍塔第五層\t",
  "龍塔第六層": "\t龍塔第六層\t",
  "龍塔頂部": "\t龍塔頂部      ",
  "焦土森林村莊外": "\t焦土森林村莊外\t   ",
  "焦土森林村莊中": "      焦土森林村莊中  ",
  "死亡之谷中": "\t死亡之谷中\t",
  "死亡之谷城堡前": "\t死亡之谷城堡前\t ",
  "遭遇碧娜維姬": "\t遭遇碧娜維姬\t",
  "趕回瓦爾克麗城": "\t趕回瓦爾克麗城\t  ",
  "保衛瓦爾克麗城": "\t保衛瓦爾克麗城\t    ",
  "治癒維斯塔女帝": "\t治癒維斯塔女帝\t",
  "前往斯德林海峽": "\t前往斯德林海峽\t  ",
  "斯德林海峽": "\t斯德林海峽\t",
  "拉那洛城外": "\t拉那洛城外\t",
  "拉那洛城內": "\t拉那洛城內\t",
  "時空異變": "       時空異變    ",
  "異世界的碧娜維姬": "    異世界的碧娜維姬\t  ",
  "究極女神": "\t究極女神      "
};
