// Generated by scripts/generate-class-catalog.mjs from reverse/parsed/native/promotion-table.json. Do not hand-edit.
export const NIA_CHARACTER_RECORD = 46 as const;

export const PROMOTION_DIALOGUE_TEXT = {
  "niaQuestion": "我的經驗值已達到轉職的目標，\n應該選擇甚麼職業？",
  "niaGrant": "現在我在水神「愛西斯」的面前，\n授予妳新的職業．",
  "teammateRequest": "我的經驗值已達到轉職的目標，\n請主將授我新的職業．"
} as const;
