// Generated by scripts/generate-resource-manifest.mjs. Do not hand-edit.

export const RESOURCE_MANIFEST_VERSION = 1 as const;
export const RESOURCE_MANIFEST_IDENTITY = "4033e93a2ed4112246aeb23b15687cf81d87710dcedf734075a52f3ea8fecf97" as const;
export const RESOURCE_MANIFEST_URL = "/assets/original/resource-manifest.v1.json" as const;
