// Generated by scripts/generate-resource-manifest.mjs. Do not hand-edit.

export const RESOURCE_MANIFEST_VERSION = 1 as const;
export const RESOURCE_MANIFEST_IDENTITY = "2c37ab92fbc369d6aede8feb186975e3dc50601717e0b4cf381f16edae2e7cec" as const;
export const RESOURCE_MANIFEST_URL = "/assets/original/resource-manifest.v1.json" as const;
