// Generated by scripts/generate-resource-manifest.mjs. Do not hand-edit.

export const RESOURCE_MANIFEST_VERSION = 1 as const;
export const RESOURCE_MANIFEST_IDENTITY = "ca15de3c0c31a172f173f8398dfb411d0529418bd74e86bf02740d9397a4d3bd" as const;
export const RESOURCE_MANIFEST_URL = "/assets/original/resource-manifest.v1.json" as const;
