// Generated by scripts/generate-stage0-music.mjs; do not edit by hand.
export const STAGE0_MUSIC_SEAM_CROSSFADE_FRAMES = 1024;
export const STAGE0_MUSIC_SEAM_SAMPLE_RATE = 44100;
export const STAGE0_MUSIC_SEAM_CROSSFADE_SECONDS = 0.023219954648526078;
