// Generated by scripts/generate-stage1-actions.mjs from native technique evidence.
// Do not hand-edit.
export const STAGE1_ACTION_DEFINITIONS = {
  "lightning-1": {
    "id": "lightning-1",
    "nativeCode": "1L",
    "label": "初級落雷",
    "kind": "technique",
    "target": "enemy",
    "range": {
      "mode": 0,
      "selectionRadius": 4,
      "effectRadius": 3
    },
    "damage": {
      "type": "magic-area",
      "byRangeValue": {
        "1": 20,
        "2": 35,
        "3": 50
      }
    },
    "experience": {
      "addKillReward": true
    },
    "presentationId": "lightning-1"
  },
  "ice-1": {
    "id": "ice-1",
    "nativeCode": "1C",
    "label": "初級冰雪",
    "kind": "technique",
    "target": "self-area",
    "range": {
      "mode": 0,
      "effectRadius": 3
    },
    "displacement": {
      "directions": [
        "down",
        "up",
        "left",
        "right"
      ],
      "requireLowerRangeValue": true
    },
    "experience": {
      "base": 8,
      "randomMinimum": 0,
      "randomMaximum": 1
    },
    "presentationId": "ice-1"
  },
  "recovery-1": {
    "id": "recovery-1",
    "nativeCode": "1I",
    "label": "初級回復",
    "kind": "technique",
    "target": "ally",
    "range": {
      "mode": 0,
      "selectionRadius": 4,
      "effectRadius": 3
    },
    "healing": {
      "type": "magic-area",
      "byRangeValue": {
        "1": 30,
        "2": 45,
        "3": 60
      }
    },
    "experience": {
      "base": 8,
      "randomMinimum": 0,
      "randomMaximum": 1,
      "divisor": 50,
      "quotientCap": 8
    },
    "presentationId": "recovery-1"
  },
  "dispel": {
    "id": "dispel",
    "nativeCode": "TR",
    "label": "破邪",
    "kind": "technique",
    "target": "ally",
    "range": {
      "mode": 0,
      "selectionRadius": 7
    },
    "cleanse": {
      "statuses": [
        "confusion",
        "attackDown",
        "defenseDown",
        "poison",
        "techniqueSeal"
      ],
      "frozen": true
    },
    "experience": {
      "base": 14,
      "randomMinimum": 0,
      "randomMaximum": 3
    },
    "presentationId": "dispel"
  }
} as const;

export type Stage1ActionId = keyof typeof STAGE1_ACTION_DEFINITIONS;

export const STAGE1_ACTION_PRESENTATION = {
  "lightning1": {
    "code": "1L",
    "entry": "1000:5DB2",
    "effectRadius": 3,
    "audioRequests": [
      {
        "resource": "E/43",
        "entry": "0000:0224",
        "afterFixedWaitNativeTicks": 80
      }
    ],
    "phases": [
      {
        "resource": "MAGIC/8",
        "descriptorSequence": [
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          }
        ],
        "drawCount": 8,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 80,
        "anchorOffsetSequence": [
          {
            "x": 8,
            "y": 8
          },
          {
            "x": 7,
            "y": 7
          },
          {
            "x": 6,
            "y": 6
          },
          {
            "x": 5,
            "y": 5
          },
          {
            "x": 4,
            "y": 4
          },
          {
            "x": 3,
            "y": 3
          },
          {
            "x": 2,
            "y": 2
          },
          {
            "x": 1,
            "y": 1
          }
        ],
        "motion": "DS:5234 starts at the selected cell +408 and shifts -51 after each draw, moving the cloud anchor from (+8,+8) through (+1,+1)"
      },
      {
        "resource": "MAGIC/8",
        "descriptorSequence": [
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          },
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          },
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          },
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          }
        ],
        "drawCount": 16,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 160
      },
      {
        "resource": "MAGIC/8",
        "descriptorSequence": [
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          }
        ],
        "drawCount": 8,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 80,
        "anchorOffsetSequence": [
          {
            "x": -1,
            "y": -1
          },
          {
            "x": -2,
            "y": -2
          },
          {
            "x": -3,
            "y": -3
          },
          {
            "x": -4,
            "y": -4
          },
          {
            "x": -5,
            "y": -5
          },
          {
            "x": -6,
            "y": -6
          },
          {
            "x": -7,
            "y": -7
          },
          {
            "x": -8,
            "y": -8
          }
        ],
        "motion": "DS:5234 continues shifting -51 after the centered body, moving the cloud anchor from (-1,-1) through (-8,-8)"
      }
    ],
    "commonHit": {
      "resource": "MAGIC/31",
      "rangeMapMaximumMinusOne": 2,
      "sweepWidth": 9,
      "iterations": 11,
      "descriptors": [
        {
          "address": "DS:6BF3",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            5
          ],
          "low7BitFrameIndices": [
            4
          ]
        },
        {
          "address": "DS:6BFD",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            6
          ],
          "low7BitFrameIndices": [
            5
          ]
        }
      ],
      "runtimeTileCodes": [
        5,
        6
      ],
      "waitPerWaveDrawNativeTicks": 2,
      "waveDrawsPerIteration": 2,
      "rangeWaveFixedGraphicWaitNativeTicks": 44,
      "cleanup": {
        "resource": "MAGIC/6",
        "descriptorSequence": [
          {
            "address": "DS:6B8F",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              1
            ],
            "low7BitFrameIndices": [
              0
            ]
          },
          {
            "address": "DS:6B99",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              2
            ],
            "low7BitFrameIndices": [
              1
            ]
          },
          {
            "address": "DS:6BA3",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              3
            ],
            "low7BitFrameIndices": [
              2
            ]
          },
          {
            "address": "DS:6BAD",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              4
            ],
            "low7BitFrameIndices": [
              3
            ]
          },
          {
            "address": "DS:6BB7",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              5
            ],
            "low7BitFrameIndices": [
              4
            ]
          }
        ],
        "drawCount": 5,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 50,
        "pointerTable": "DS:6B79",
        "drawScope": "each descriptor is drawn on all occupied enemy-side cells, then flushed/waited once"
      },
      "fixedGraphicWaitNativeTicks": 94
    },
    "fixedGraphicWaitNativeTicks": 414
  },
  "ice1": {
    "code": "1C",
    "effectRadius": 3,
    "cycles": 2,
    "rangeValueSequence": [
      2,
      1
    ],
    "distanceFromCenterSequence": [
      1,
      2
    ],
    "soundRequests": 2,
    "drawCount": 12,
    "fixedGraphicWaitNativeTicks": 120,
    "cycle": {
      "resource": "MAGIC/10",
      "descriptorSequence": [
        {
          "address": "DS:17CA",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:17D4",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            2
          ],
          "low7BitFrameIndices": [
            1
          ]
        },
        {
          "address": "DS:17DE",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            3
          ],
          "low7BitFrameIndices": [
            2
          ]
        },
        {
          "address": "DS:17E8",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            4
          ],
          "low7BitFrameIndices": [
            3
          ]
        },
        {
          "address": "DS:17F2",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            5
          ],
          "low7BitFrameIndices": [
            4
          ]
        },
        {
          "address": "DS:17FC",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            6
          ],
          "low7BitFrameIndices": [
            5
          ]
        }
      ],
      "drawCount": 6,
      "waitPerDrawNativeTicks": 10,
      "fixedGraphicWaitNativeTicks": 60,
      "audioRequestTiming": "once at the start of every expansion cycle",
      "drawScope": "each of the six descriptors is drawn on cells in the current range-map stage and then flushed/waited once"
    },
    "audioResource": "UN/50"
  },
  "recovery1": {
    "family": "I",
    "visibleName": "回復",
    "commonEntry": "1000:6EE0",
    "dispatchEntry": "1000:5DA4",
    "actionCodes": [
      "1I",
      "2I",
      "3I"
    ],
    "audioRequests": [
      {
        "resource": "E/36",
        "entry": "0000:0220",
        "afterFixedWaitNativeTicks": 0
      }
    ],
    "presentation": {
      "resource": "MAGIC/20",
      "descriptorSequence": [
        {
          "address": "DS:6C41",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:6C41",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:6C41",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:6C4B",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            2
          ],
          "low7BitFrameIndices": [
            1
          ]
        },
        {
          "address": "DS:6C55",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            3
          ],
          "low7BitFrameIndices": [
            2
          ]
        },
        {
          "address": "DS:6C5F",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            4
          ],
          "low7BitFrameIndices": [
            3
          ]
        },
        {
          "address": "DS:6C69",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            5
          ],
          "low7BitFrameIndices": [
            4
          ]
        },
        {
          "address": "DS:6C73",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            6
          ],
          "low7BitFrameIndices": [
            5
          ]
        },
        {
          "address": "DS:6C7D",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            7
          ],
          "low7BitFrameIndices": [
            6
          ]
        },
        {
          "address": "DS:6C87",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            8
          ],
          "low7BitFrameIndices": [
            7
          ]
        },
        {
          "address": "DS:6C91",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            9
          ],
          "low7BitFrameIndices": [
            8
          ]
        },
        {
          "address": "DS:6C9B",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            10
          ],
          "low7BitFrameIndices": [
            9
          ]
        },
        {
          "address": "DS:6C41",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:6C41",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:6C41",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:6CA5",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            0
          ],
          "low7BitFrameIndices": [
            null
          ]
        },
        {
          "address": "DS:6CA5",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            0
          ],
          "low7BitFrameIndices": [
            null
          ]
        }
      ],
      "drawCount": 17,
      "waitPerDrawNativeTicks": 15,
      "fixedGraphicWaitNativeTicks": 255,
      "pointerTable": "DS:6C1D",
      "drawScope": "each descriptor is drawn without an individual wait on every occupied same-side cell, then the whole map effect is flushed and waits once"
    },
    "fixedGraphicWaitNativeTicks": 255,
    "tierPresentationDifferences": false,
    "settlementBoundary": "1000:6FFE scans and heals same-side cells only after all 17 presentation stages; tier changes range/heal values, not graphics, sound or timing"
  },
  "dispel": {
    "code": "TR",
    "visibleName": "破邪",
    "wrapper": "0000:CF6D",
    "presentationEntry": "1000:7AC0",
    "phases": [
      {
        "drawCount": 24,
        "runtimeTileCodeStates": [
          [
            0,
            0,
            0,
            0,
            0
          ],
          [
            1,
            0,
            0,
            0,
            0
          ],
          [
            2,
            0,
            0,
            0,
            0
          ],
          [
            3,
            0,
            0,
            0,
            0
          ],
          [
            4,
            0,
            0,
            0,
            0
          ],
          [
            5,
            1,
            0,
            0,
            0
          ],
          [
            6,
            2,
            0,
            0,
            0
          ],
          [
            7,
            3,
            0,
            0,
            0
          ],
          [
            8,
            14,
            0,
            0,
            0
          ],
          [
            9,
            15,
            1,
            0,
            0
          ],
          [
            10,
            16,
            2,
            0,
            0
          ],
          [
            11,
            17,
            3,
            0,
            0
          ],
          [
            12,
            18,
            4,
            0,
            0
          ],
          [
            13,
            19,
            5,
            1,
            0
          ],
          [
            0,
            20,
            6,
            2,
            0
          ],
          [
            0,
            21,
            7,
            3,
            0
          ],
          [
            0,
            22,
            8,
            14,
            0
          ],
          [
            0,
            0,
            9,
            15,
            1
          ],
          [
            0,
            0,
            10,
            16,
            2
          ],
          [
            0,
            0,
            11,
            17,
            3
          ],
          [
            0,
            0,
            12,
            18,
            23
          ],
          [
            0,
            0,
            13,
            19,
            23
          ],
          [
            0,
            0,
            0,
            20,
            23
          ],
          [
            0,
            0,
            0,
            21,
            23
          ]
        ],
        "waitPerDrawNativeTicks": 5,
        "fixedGraphicWaitNativeTicks": 120,
        "behavior": "five 1x1 streams enter at stagger thresholds; the first four clear on their table terminator"
      },
      {
        "drawCount": 26,
        "runtimeTileCodeStates": [
          [
            0,
            0,
            0,
            22,
            23
          ],
          [
            0,
            0,
            0,
            22,
            24
          ],
          [
            0,
            0,
            0,
            22,
            25
          ],
          [
            0,
            0,
            0,
            22,
            26
          ],
          [
            0,
            0,
            0,
            22,
            27
          ],
          [
            0,
            0,
            0,
            22,
            28
          ],
          [
            0,
            0,
            0,
            22,
            29
          ],
          [
            0,
            0,
            0,
            22,
            30
          ],
          [
            0,
            0,
            0,
            22,
            31
          ],
          [
            0,
            0,
            0,
            22,
            32
          ],
          [
            0,
            0,
            0,
            22,
            33
          ],
          [
            0,
            0,
            0,
            22,
            34
          ],
          [
            0,
            0,
            0,
            22,
            35
          ],
          [
            0,
            0,
            0,
            22,
            36
          ],
          [
            0,
            0,
            0,
            22,
            37
          ],
          [
            0,
            0,
            0,
            22,
            38
          ],
          [
            0,
            0,
            0,
            22,
            39
          ],
          [
            0,
            0,
            0,
            22,
            40
          ],
          [
            0,
            0,
            0,
            22,
            41
          ],
          [
            0,
            0,
            0,
            22,
            42
          ],
          [
            0,
            0,
            0,
            22,
            43
          ],
          [
            0,
            0,
            0,
            22,
            44
          ],
          [
            0,
            0,
            0,
            22,
            45
          ],
          [
            0,
            0,
            0,
            22,
            46
          ],
          [
            0,
            0,
            0,
            22,
            47
          ],
          [
            0,
            0,
            0,
            22,
            0
          ]
        ],
        "waitPerDrawNativeTicks": 5,
        "fixedGraphicWaitNativeTicks": 130,
        "behavior": "tile 22 remains in the fourth row while the fifth row advances 23..47, followed by one clear draw"
      }
    ],
    "audioRequests": [],
    "fixedGraphicWaitNativeTicks": 250,
    "dynamicPresentation": {
      "resource": "UN/57",
      "descriptor": {
        "address": "DS:71DB",
        "xOffset": 0,
        "yOffset": -4,
        "width": 1,
        "height": 5,
        "tileCodes": [
          0,
          0,
          0,
          0,
          0
        ],
        "low7BitFrameIndices": [
          null,
          null,
          null,
          null,
          null
        ]
      },
      "phase1": {
        "drawCount": 24,
        "runtimeTileCodeStates": [
          [
            0,
            0,
            0,
            0,
            0
          ],
          [
            1,
            0,
            0,
            0,
            0
          ],
          [
            2,
            0,
            0,
            0,
            0
          ],
          [
            3,
            0,
            0,
            0,
            0
          ],
          [
            4,
            0,
            0,
            0,
            0
          ],
          [
            5,
            1,
            0,
            0,
            0
          ],
          [
            6,
            2,
            0,
            0,
            0
          ],
          [
            7,
            3,
            0,
            0,
            0
          ],
          [
            8,
            14,
            0,
            0,
            0
          ],
          [
            9,
            15,
            1,
            0,
            0
          ],
          [
            10,
            16,
            2,
            0,
            0
          ],
          [
            11,
            17,
            3,
            0,
            0
          ],
          [
            12,
            18,
            4,
            0,
            0
          ],
          [
            13,
            19,
            5,
            1,
            0
          ],
          [
            0,
            20,
            6,
            2,
            0
          ],
          [
            0,
            21,
            7,
            3,
            0
          ],
          [
            0,
            22,
            8,
            14,
            0
          ],
          [
            0,
            0,
            9,
            15,
            1
          ],
          [
            0,
            0,
            10,
            16,
            2
          ],
          [
            0,
            0,
            11,
            17,
            3
          ],
          [
            0,
            0,
            12,
            18,
            23
          ],
          [
            0,
            0,
            13,
            19,
            23
          ],
          [
            0,
            0,
            0,
            20,
            23
          ],
          [
            0,
            0,
            0,
            21,
            23
          ]
        ],
        "waitPerDrawNativeTicks": 5,
        "fixedGraphicWaitNativeTicks": 120,
        "behavior": "five 1x1 streams enter at stagger thresholds; the first four clear on their table terminator"
      },
      "phase2": {
        "drawCount": 26,
        "runtimeTileCodeStates": [
          [
            0,
            0,
            0,
            22,
            23
          ],
          [
            0,
            0,
            0,
            22,
            24
          ],
          [
            0,
            0,
            0,
            22,
            25
          ],
          [
            0,
            0,
            0,
            22,
            26
          ],
          [
            0,
            0,
            0,
            22,
            27
          ],
          [
            0,
            0,
            0,
            22,
            28
          ],
          [
            0,
            0,
            0,
            22,
            29
          ],
          [
            0,
            0,
            0,
            22,
            30
          ],
          [
            0,
            0,
            0,
            22,
            31
          ],
          [
            0,
            0,
            0,
            22,
            32
          ],
          [
            0,
            0,
            0,
            22,
            33
          ],
          [
            0,
            0,
            0,
            22,
            34
          ],
          [
            0,
            0,
            0,
            22,
            35
          ],
          [
            0,
            0,
            0,
            22,
            36
          ],
          [
            0,
            0,
            0,
            22,
            37
          ],
          [
            0,
            0,
            0,
            22,
            38
          ],
          [
            0,
            0,
            0,
            22,
            39
          ],
          [
            0,
            0,
            0,
            22,
            40
          ],
          [
            0,
            0,
            0,
            22,
            41
          ],
          [
            0,
            0,
            0,
            22,
            42
          ],
          [
            0,
            0,
            0,
            22,
            43
          ],
          [
            0,
            0,
            0,
            22,
            44
          ],
          [
            0,
            0,
            0,
            22,
            45
          ],
          [
            0,
            0,
            0,
            22,
            46
          ],
          [
            0,
            0,
            0,
            22,
            47
          ],
          [
            0,
            0,
            0,
            22,
            0
          ]
        ],
        "waitPerDrawNativeTicks": 5,
        "fixedGraphicWaitNativeTicks": 130,
        "behavior": "tile 22 remains in the fourth row while the fifth row advances 23..47, followed by one clear draw"
      },
      "fixedGraphicWaitNativeTicks": 250
    },
    "mutation": "clear bit15 at unit+12/+10/+0E, then write 7FFFh to unit+14/+16"
  }
} as const;

export const STAGE1_ACTION_PRESENTATION_ASSETS = {
  "lightning1": {
    "main": [
      "/assets/original/map-actions/lightning-1/main/00.png",
      "/assets/original/map-actions/lightning-1/main/01.png",
      "/assets/original/map-actions/lightning-1/main/02.png",
      "/assets/original/map-actions/lightning-1/main/03.png",
      "/assets/original/map-actions/lightning-1/main/04.png",
      "/assets/original/map-actions/lightning-1/main/05.png",
      "/assets/original/map-actions/lightning-1/main/06.png",
      "/assets/original/map-actions/lightning-1/main/07.png",
      "/assets/original/map-actions/lightning-1/main/08.png",
      "/assets/original/map-actions/lightning-1/main/09.png",
      "/assets/original/map-actions/lightning-1/main/10.png",
      "/assets/original/map-actions/lightning-1/main/11.png",
      "/assets/original/map-actions/lightning-1/main/12.png",
      "/assets/original/map-actions/lightning-1/main/13.png",
      "/assets/original/map-actions/lightning-1/main/14.png",
      "/assets/original/map-actions/lightning-1/main/15.png",
      "/assets/original/map-actions/lightning-1/main/16.png",
      "/assets/original/map-actions/lightning-1/main/17.png",
      "/assets/original/map-actions/lightning-1/main/18.png",
      "/assets/original/map-actions/lightning-1/main/19.png",
      "/assets/original/map-actions/lightning-1/main/20.png",
      "/assets/original/map-actions/lightning-1/main/21.png",
      "/assets/original/map-actions/lightning-1/main/22.png",
      "/assets/original/map-actions/lightning-1/main/23.png",
      "/assets/original/map-actions/lightning-1/main/24.png",
      "/assets/original/map-actions/lightning-1/main/25.png",
      "/assets/original/map-actions/lightning-1/main/26.png",
      "/assets/original/map-actions/lightning-1/main/27.png",
      "/assets/original/map-actions/lightning-1/main/28.png",
      "/assets/original/map-actions/lightning-1/main/29.png",
      "/assets/original/map-actions/lightning-1/main/30.png",
      "/assets/original/map-actions/lightning-1/main/31.png",
      "/assets/original/map-actions/lightning-1/main/32.png",
      "/assets/original/map-actions/lightning-1/main/33.png",
      "/assets/original/map-actions/lightning-1/main/34.png",
      "/assets/original/map-actions/lightning-1/main/35.png",
      "/assets/original/map-actions/lightning-1/main/36.png",
      "/assets/original/map-actions/lightning-1/main/37.png",
      "/assets/original/map-actions/lightning-1/main/38.png",
      "/assets/original/map-actions/lightning-1/main/39.png",
      "/assets/original/map-actions/lightning-1/main/40.png",
      "/assets/original/map-actions/lightning-1/main/41.png",
      "/assets/original/map-actions/lightning-1/main/42.png",
      "/assets/original/map-actions/lightning-1/main/43.png",
      "/assets/original/map-actions/lightning-1/main/44.png",
      "/assets/original/map-actions/lightning-1/main/45.png",
      "/assets/original/map-actions/lightning-1/main/46.png",
      "/assets/original/map-actions/lightning-1/main/47.png",
      "/assets/original/map-actions/lightning-1/main/48.png",
      "/assets/original/map-actions/lightning-1/main/49.png",
      "/assets/original/map-actions/lightning-1/main/50.png",
      "/assets/original/map-actions/lightning-1/main/51.png",
      "/assets/original/map-actions/lightning-1/main/52.png",
      "/assets/original/map-actions/lightning-1/main/53.png",
      "/assets/original/map-actions/lightning-1/main/54.png",
      "/assets/original/map-actions/lightning-1/main/55.png"
    ],
    "hit": [
      "/assets/original/map-actions/lightning-1/hit/00.png",
      "/assets/original/map-actions/lightning-1/hit/01.png",
      "/assets/original/map-actions/lightning-1/hit/02.png",
      "/assets/original/map-actions/lightning-1/hit/03.png",
      "/assets/original/map-actions/lightning-1/hit/04.png",
      "/assets/original/map-actions/lightning-1/hit/05.png",
      "/assets/original/map-actions/lightning-1/hit/06.png",
      "/assets/original/map-actions/lightning-1/hit/07.png",
      "/assets/original/map-actions/lightning-1/hit/08.png",
      "/assets/original/map-actions/lightning-1/hit/09.png",
      "/assets/original/map-actions/lightning-1/hit/10.png",
      "/assets/original/map-actions/lightning-1/hit/11.png"
    ],
    "cleanup": [
      "/assets/original/map-actions/lightning-1/cleanup/00.png",
      "/assets/original/map-actions/lightning-1/cleanup/01.png",
      "/assets/original/map-actions/lightning-1/cleanup/02.png",
      "/assets/original/map-actions/lightning-1/cleanup/03.png",
      "/assets/original/map-actions/lightning-1/cleanup/04.png",
      "/assets/original/map-actions/lightning-1/cleanup/05.png",
      "/assets/original/map-actions/lightning-1/cleanup/06.png",
      "/assets/original/map-actions/lightning-1/cleanup/07.png",
      "/assets/original/map-actions/lightning-1/cleanup/08.png",
      "/assets/original/map-actions/lightning-1/cleanup/09.png"
    ]
  },
  "ice1": {
    "expansion": [
      "/assets/original/map-actions/ice-1/expansion/00.png",
      "/assets/original/map-actions/ice-1/expansion/01.png",
      "/assets/original/map-actions/ice-1/expansion/02.png",
      "/assets/original/map-actions/ice-1/expansion/03.png",
      "/assets/original/map-actions/ice-1/expansion/04.png",
      "/assets/original/map-actions/ice-1/expansion/05.png"
    ]
  },
  "recovery1": {
    "effect": [
      "/assets/original/map-actions/recovery-1/effect/00.png",
      "/assets/original/map-actions/recovery-1/effect/01.png",
      "/assets/original/map-actions/recovery-1/effect/02.png",
      "/assets/original/map-actions/recovery-1/effect/03.png",
      "/assets/original/map-actions/recovery-1/effect/04.png",
      "/assets/original/map-actions/recovery-1/effect/05.png",
      "/assets/original/map-actions/recovery-1/effect/06.png",
      "/assets/original/map-actions/recovery-1/effect/07.png",
      "/assets/original/map-actions/recovery-1/effect/08.png",
      "/assets/original/map-actions/recovery-1/effect/09.png"
    ]
  },
  "dispel": {
    "effect": [
      "/assets/original/map-actions/dispel/effect/00.png",
      "/assets/original/map-actions/dispel/effect/01.png",
      "/assets/original/map-actions/dispel/effect/02.png",
      "/assets/original/map-actions/dispel/effect/03.png",
      "/assets/original/map-actions/dispel/effect/04.png",
      "/assets/original/map-actions/dispel/effect/05.png",
      "/assets/original/map-actions/dispel/effect/06.png",
      "/assets/original/map-actions/dispel/effect/07.png",
      "/assets/original/map-actions/dispel/effect/08.png",
      "/assets/original/map-actions/dispel/effect/09.png",
      "/assets/original/map-actions/dispel/effect/10.png",
      "/assets/original/map-actions/dispel/effect/11.png",
      "/assets/original/map-actions/dispel/effect/12.png",
      "/assets/original/map-actions/dispel/effect/13.png",
      "/assets/original/map-actions/dispel/effect/14.png",
      "/assets/original/map-actions/dispel/effect/15.png",
      "/assets/original/map-actions/dispel/effect/16.png",
      "/assets/original/map-actions/dispel/effect/17.png",
      "/assets/original/map-actions/dispel/effect/18.png",
      "/assets/original/map-actions/dispel/effect/19.png",
      "/assets/original/map-actions/dispel/effect/20.png",
      "/assets/original/map-actions/dispel/effect/21.png",
      "/assets/original/map-actions/dispel/effect/22.png",
      "/assets/original/map-actions/dispel/effect/23.png",
      "/assets/original/map-actions/dispel/effect/24.png",
      "/assets/original/map-actions/dispel/effect/25.png",
      "/assets/original/map-actions/dispel/effect/26.png",
      "/assets/original/map-actions/dispel/effect/27.png",
      "/assets/original/map-actions/dispel/effect/28.png",
      "/assets/original/map-actions/dispel/effect/29.png",
      "/assets/original/map-actions/dispel/effect/30.png",
      "/assets/original/map-actions/dispel/effect/31.png",
      "/assets/original/map-actions/dispel/effect/32.png",
      "/assets/original/map-actions/dispel/effect/33.png",
      "/assets/original/map-actions/dispel/effect/34.png",
      "/assets/original/map-actions/dispel/effect/35.png",
      "/assets/original/map-actions/dispel/effect/36.png",
      "/assets/original/map-actions/dispel/effect/37.png",
      "/assets/original/map-actions/dispel/effect/38.png",
      "/assets/original/map-actions/dispel/effect/39.png",
      "/assets/original/map-actions/dispel/effect/40.png",
      "/assets/original/map-actions/dispel/effect/41.png",
      "/assets/original/map-actions/dispel/effect/42.png",
      "/assets/original/map-actions/dispel/effect/43.png",
      "/assets/original/map-actions/dispel/effect/44.png",
      "/assets/original/map-actions/dispel/effect/45.png",
      "/assets/original/map-actions/dispel/effect/46.png"
    ]
  }
} as const;

export const STAGE1_ACTION_AUDIO_ASSETS = {
  "e-36": "/assets/original/audio/e/36.wav",
  "e-43": "/assets/original/audio/e/43.wav",
  "un-50": "/assets/original/audio/un/50.wav"
} as const;
