// Generated by scripts/generate-stage1-actions.mjs from native technique evidence.
// Do not hand-edit.
export const STAGE1_ACTION_DEFINITIONS = {
  "lightning-1": {
    "id": "lightning-1",
    "nativeCode": "1L",
    "label": "初級落雷",
    "kind": "technique",
    "target": "enemy",
    "range": {
      "mode": 0,
      "selectionRadius": 4,
      "effectRadius": 3
    },
    "damage": {
      "type": "magic-area",
      "byRangeValue": {
        "1": 20,
        "2": 35,
        "3": 50
      }
    },
    "experience": {
      "addKillReward": true
    },
    "presentationId": "lightning-1"
  },
  "ice-1": {
    "id": "ice-1",
    "nativeCode": "1C",
    "label": "初級冰雪",
    "kind": "technique",
    "target": "area",
    "range": {
      "mode": 0,
      "selectionRadius": 2,
      "effectRadius": 3
    },
    "displacement": {
      "directions": [
        "down",
        "up",
        "left",
        "right"
      ],
      "requireLowerRangeValue": true
    },
    "experience": {
      "base": 8,
      "randomMinimum": 0,
      "randomMaximum": 1
    },
    "presentationId": "ice-1"
  }
} as const;

export type Stage1ActionId = keyof typeof STAGE1_ACTION_DEFINITIONS;

export const STAGE1_ACTION_PRESENTATION = {
  "lightning1": {
    "code": "1L",
    "entry": "1000:5DB2",
    "effectRadius": 3,
    "audioRequests": [
      {
        "resource": "E/43",
        "entry": "0000:0224",
        "afterFixedWaitNativeTicks": 80
      }
    ],
    "phases": [
      {
        "resource": "MAGIC/8",
        "descriptorSequence": [
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          }
        ],
        "drawCount": 8,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 80,
        "anchorOffsetSequence": [
          {
            "x": 8,
            "y": 8
          },
          {
            "x": 7,
            "y": 7
          },
          {
            "x": 6,
            "y": 6
          },
          {
            "x": 5,
            "y": 5
          },
          {
            "x": 4,
            "y": 4
          },
          {
            "x": 3,
            "y": 3
          },
          {
            "x": 2,
            "y": 2
          },
          {
            "x": 1,
            "y": 1
          }
        ],
        "motion": "DS:5234 starts at the selected cell +408 and shifts -51 after each draw, moving the cloud anchor from (+8,+8) through (+1,+1)"
      },
      {
        "resource": "MAGIC/8",
        "descriptorSequence": [
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          },
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          },
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          },
          {
            "address": "DS:61C8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            "low7BitFrameIndices": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
            ]
          },
          {
            "address": "DS:61E8",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24
            ],
            "low7BitFrameIndices": [
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23
            ]
          },
          {
            "address": "DS:6228",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48
            ],
            "low7BitFrameIndices": [
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47
            ]
          },
          {
            "address": "DS:6208",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36
            ],
            "low7BitFrameIndices": [
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35
            ]
          }
        ],
        "drawCount": 16,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 160
      },
      {
        "resource": "MAGIC/8",
        "descriptorSequence": [
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          },
          {
            "address": "DS:6248",
            "xOffset": -1,
            "yOffset": -2,
            "width": 4,
            "height": 3,
            "tileCodes": [
              49,
              50,
              51,
              52,
              0,
              0,
              0,
              0,
              53,
              54,
              55,
              56
            ],
            "low7BitFrameIndices": [
              48,
              49,
              50,
              51,
              null,
              null,
              null,
              null,
              52,
              53,
              54,
              55
            ]
          }
        ],
        "drawCount": 8,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 80,
        "anchorOffsetSequence": [
          {
            "x": -1,
            "y": -1
          },
          {
            "x": -2,
            "y": -2
          },
          {
            "x": -3,
            "y": -3
          },
          {
            "x": -4,
            "y": -4
          },
          {
            "x": -5,
            "y": -5
          },
          {
            "x": -6,
            "y": -6
          },
          {
            "x": -7,
            "y": -7
          },
          {
            "x": -8,
            "y": -8
          }
        ],
        "motion": "DS:5234 continues shifting -51 after the centered body, moving the cloud anchor from (-1,-1) through (-8,-8)"
      }
    ],
    "commonHit": {
      "resource": "MAGIC/31",
      "rangeMapMaximumMinusOne": 2,
      "sweepWidth": 9,
      "iterations": 11,
      "descriptors": [
        {
          "address": "DS:6BF3",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            5
          ],
          "low7BitFrameIndices": [
            4
          ]
        },
        {
          "address": "DS:6BFD",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            6
          ],
          "low7BitFrameIndices": [
            5
          ]
        }
      ],
      "runtimeTileCodes": [
        5,
        6
      ],
      "waitPerWaveDrawNativeTicks": 2,
      "waveDrawsPerIteration": 2,
      "rangeWaveFixedGraphicWaitNativeTicks": 44,
      "cleanup": {
        "resource": "MAGIC/6",
        "descriptorSequence": [
          {
            "address": "DS:6B8F",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              1
            ],
            "low7BitFrameIndices": [
              0
            ]
          },
          {
            "address": "DS:6B99",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              2
            ],
            "low7BitFrameIndices": [
              1
            ]
          },
          {
            "address": "DS:6BA3",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              3
            ],
            "low7BitFrameIndices": [
              2
            ]
          },
          {
            "address": "DS:6BAD",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              4
            ],
            "low7BitFrameIndices": [
              3
            ]
          },
          {
            "address": "DS:6BB7",
            "xOffset": 0,
            "yOffset": 0,
            "width": 1,
            "height": 1,
            "tileCodes": [
              5
            ],
            "low7BitFrameIndices": [
              4
            ]
          }
        ],
        "drawCount": 5,
        "waitPerDrawNativeTicks": 10,
        "fixedGraphicWaitNativeTicks": 50,
        "pointerTable": "DS:6B79",
        "drawScope": "each descriptor is drawn on all occupied enemy-side cells, then flushed/waited once"
      },
      "fixedGraphicWaitNativeTicks": 94
    },
    "fixedGraphicWaitNativeTicks": 414
  },
  "ice1": {
    "code": "1C",
    "effectRadius": 3,
    "cycles": 2,
    "soundRequests": 2,
    "drawCount": 12,
    "fixedGraphicWaitNativeTicks": 120,
    "cycle": {
      "resource": "MAGIC/10",
      "descriptorSequence": [
        {
          "address": "DS:17CA",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            1
          ],
          "low7BitFrameIndices": [
            0
          ]
        },
        {
          "address": "DS:17D4",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            2
          ],
          "low7BitFrameIndices": [
            1
          ]
        },
        {
          "address": "DS:17DE",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            3
          ],
          "low7BitFrameIndices": [
            2
          ]
        },
        {
          "address": "DS:17E8",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            4
          ],
          "low7BitFrameIndices": [
            3
          ]
        },
        {
          "address": "DS:17F2",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            5
          ],
          "low7BitFrameIndices": [
            4
          ]
        },
        {
          "address": "DS:17FC",
          "xOffset": 0,
          "yOffset": 0,
          "width": 1,
          "height": 1,
          "tileCodes": [
            6
          ],
          "low7BitFrameIndices": [
            5
          ]
        }
      ],
      "drawCount": 6,
      "waitPerDrawNativeTicks": 10,
      "fixedGraphicWaitNativeTicks": 60,
      "audioRequestTiming": "once at the start of every expansion cycle",
      "drawScope": "each of the six descriptors is drawn on cells in the current range-map stage and then flushed/waited once"
    },
    "audioResource": "UN/50"
  }
} as const;

export const STAGE1_ACTION_PRESENTATION_ASSETS = {
  "lightning1": {
    "main": [
      "/assets/original/map-actions/lightning-1/main/00.png",
      "/assets/original/map-actions/lightning-1/main/01.png",
      "/assets/original/map-actions/lightning-1/main/02.png",
      "/assets/original/map-actions/lightning-1/main/03.png",
      "/assets/original/map-actions/lightning-1/main/04.png",
      "/assets/original/map-actions/lightning-1/main/05.png",
      "/assets/original/map-actions/lightning-1/main/06.png",
      "/assets/original/map-actions/lightning-1/main/07.png",
      "/assets/original/map-actions/lightning-1/main/08.png",
      "/assets/original/map-actions/lightning-1/main/09.png",
      "/assets/original/map-actions/lightning-1/main/10.png",
      "/assets/original/map-actions/lightning-1/main/11.png",
      "/assets/original/map-actions/lightning-1/main/12.png",
      "/assets/original/map-actions/lightning-1/main/13.png",
      "/assets/original/map-actions/lightning-1/main/14.png",
      "/assets/original/map-actions/lightning-1/main/15.png",
      "/assets/original/map-actions/lightning-1/main/16.png",
      "/assets/original/map-actions/lightning-1/main/17.png",
      "/assets/original/map-actions/lightning-1/main/18.png",
      "/assets/original/map-actions/lightning-1/main/19.png",
      "/assets/original/map-actions/lightning-1/main/20.png",
      "/assets/original/map-actions/lightning-1/main/21.png",
      "/assets/original/map-actions/lightning-1/main/22.png",
      "/assets/original/map-actions/lightning-1/main/23.png",
      "/assets/original/map-actions/lightning-1/main/24.png",
      "/assets/original/map-actions/lightning-1/main/25.png",
      "/assets/original/map-actions/lightning-1/main/26.png",
      "/assets/original/map-actions/lightning-1/main/27.png",
      "/assets/original/map-actions/lightning-1/main/28.png",
      "/assets/original/map-actions/lightning-1/main/29.png",
      "/assets/original/map-actions/lightning-1/main/30.png",
      "/assets/original/map-actions/lightning-1/main/31.png",
      "/assets/original/map-actions/lightning-1/main/32.png",
      "/assets/original/map-actions/lightning-1/main/33.png",
      "/assets/original/map-actions/lightning-1/main/34.png",
      "/assets/original/map-actions/lightning-1/main/35.png",
      "/assets/original/map-actions/lightning-1/main/36.png",
      "/assets/original/map-actions/lightning-1/main/37.png",
      "/assets/original/map-actions/lightning-1/main/38.png",
      "/assets/original/map-actions/lightning-1/main/39.png",
      "/assets/original/map-actions/lightning-1/main/40.png",
      "/assets/original/map-actions/lightning-1/main/41.png",
      "/assets/original/map-actions/lightning-1/main/42.png",
      "/assets/original/map-actions/lightning-1/main/43.png",
      "/assets/original/map-actions/lightning-1/main/44.png",
      "/assets/original/map-actions/lightning-1/main/45.png",
      "/assets/original/map-actions/lightning-1/main/46.png",
      "/assets/original/map-actions/lightning-1/main/47.png",
      "/assets/original/map-actions/lightning-1/main/48.png",
      "/assets/original/map-actions/lightning-1/main/49.png",
      "/assets/original/map-actions/lightning-1/main/50.png",
      "/assets/original/map-actions/lightning-1/main/51.png",
      "/assets/original/map-actions/lightning-1/main/52.png",
      "/assets/original/map-actions/lightning-1/main/53.png",
      "/assets/original/map-actions/lightning-1/main/54.png",
      "/assets/original/map-actions/lightning-1/main/55.png"
    ],
    "hit": [
      "/assets/original/map-actions/lightning-1/hit/00.png",
      "/assets/original/map-actions/lightning-1/hit/01.png",
      "/assets/original/map-actions/lightning-1/hit/02.png",
      "/assets/original/map-actions/lightning-1/hit/03.png",
      "/assets/original/map-actions/lightning-1/hit/04.png",
      "/assets/original/map-actions/lightning-1/hit/05.png",
      "/assets/original/map-actions/lightning-1/hit/06.png",
      "/assets/original/map-actions/lightning-1/hit/07.png",
      "/assets/original/map-actions/lightning-1/hit/08.png",
      "/assets/original/map-actions/lightning-1/hit/09.png",
      "/assets/original/map-actions/lightning-1/hit/10.png",
      "/assets/original/map-actions/lightning-1/hit/11.png"
    ],
    "cleanup": [
      "/assets/original/map-actions/lightning-1/cleanup/00.png",
      "/assets/original/map-actions/lightning-1/cleanup/01.png",
      "/assets/original/map-actions/lightning-1/cleanup/02.png",
      "/assets/original/map-actions/lightning-1/cleanup/03.png",
      "/assets/original/map-actions/lightning-1/cleanup/04.png",
      "/assets/original/map-actions/lightning-1/cleanup/05.png",
      "/assets/original/map-actions/lightning-1/cleanup/06.png",
      "/assets/original/map-actions/lightning-1/cleanup/07.png",
      "/assets/original/map-actions/lightning-1/cleanup/08.png",
      "/assets/original/map-actions/lightning-1/cleanup/09.png"
    ]
  },
  "ice1": {
    "expansion": [
      "/assets/original/map-actions/ice-1/expansion/00.png",
      "/assets/original/map-actions/ice-1/expansion/01.png",
      "/assets/original/map-actions/ice-1/expansion/02.png",
      "/assets/original/map-actions/ice-1/expansion/03.png",
      "/assets/original/map-actions/ice-1/expansion/04.png",
      "/assets/original/map-actions/ice-1/expansion/05.png"
    ]
  }
} as const;

export const STAGE1_ACTION_AUDIO_ASSETS = {
  "e-43": "/assets/original/audio/e/43.wav",
  "un-50": "/assets/original/audio/un/50.wav"
} as const;
