import {
  STAGE0_ACTION_AUDIO_ASSETS,
  STAGE0_ACTION_PRESENTATION_ASSETS,
} from "./stage0-actions.generated";
import {
  STAGE1_ACTION_AUDIO_ASSETS,
  STAGE1_ACTION_PRESENTATION_ASSETS,
} from "./stage1-actions.generated";

/**
 * The technique laboratory renders native resource records, while the campaign
 * catalogs presentation assets by semantic action. Keep the laboratory on the
 * campaign's generated URLs so it cannot become a second, independently mapped
 * visual truth.
 */
export const TECHNIQUE_LAB_FORMAL_GRAPHIC_ASSETS = {
  "MAGIC/8": STAGE1_ACTION_PRESENTATION_ASSETS.lightning1.main,
  "MAGIC/31": STAGE1_ACTION_PRESENTATION_ASSETS.lightning1.hit,
  "MAGIC/6": STAGE1_ACTION_PRESENTATION_ASSETS.lightning1.cleanup,
  "MAGIC/47": STAGE1_ACTION_PRESENTATION_ASSETS.lightning2.primary,
  "MAGIC/48": STAGE1_ACTION_PRESENTATION_ASSETS.lightning2.column,
  "MAGIC/24": STAGE1_ACTION_PRESENTATION_ASSETS.lightning2.hit,
  "MAGIC/3": STAGE1_ACTION_PRESENTATION_ASSETS.lightning3.cloud,
  "MAGIC/4": STAGE1_ACTION_PRESENTATION_ASSETS.lightning3.column,
  "MAGIC/25": STAGE1_ACTION_PRESENTATION_ASSETS.lightning3.hit,
  "MAGIC/39": STAGE1_ACTION_PRESENTATION_ASSETS.lightning4.primary,
  "MAGIC/40": STAGE1_ACTION_PRESENTATION_ASSETS.lightning4.column,
  "MAGIC/26": STAGE1_ACTION_PRESENTATION_ASSETS.lightning4.hit,
  "MAGIC/10": STAGE1_ACTION_PRESENTATION_ASSETS.ice1.expansion,
  "MAGIC/22": STAGE0_ACTION_PRESENTATION_ASSETS.fire1.effect,
  "MAGIC/23": STAGE1_ACTION_PRESENTATION_ASSETS.fire2.effect,
  "MAGIC/27": STAGE1_ACTION_PRESENTATION_ASSETS.fire3.effect,
  "MAGIC/30": STAGE1_ACTION_PRESENTATION_ASSETS.fire4.ground,
  "MAGIC/28": STAGE1_ACTION_PRESENTATION_ASSETS.fire4.column,
  "MAGIC/29": STAGE1_ACTION_PRESENTATION_ASSETS.fire4.finish,
  "UN/61": STAGE0_ACTION_PRESENTATION_ASSETS.heal1.primary,
  "MAGIC/0": STAGE0_ACTION_PRESENTATION_ASSETS.heal1.tail,
  "MAGIC/37": STAGE1_ACTION_PRESENTATION_ASSETS.heal2.primary,
  "MAGIC/42": STAGE1_ACTION_PRESENTATION_ASSETS.heal3.outer,
  "MAGIC/41": STAGE1_ACTION_PRESENTATION_ASSETS.heal3.loop,
  "MAGIC/20": STAGE1_ACTION_PRESENTATION_ASSETS.recovery1.effect,
  "MAGIC/16": STAGE1_ACTION_PRESENTATION_ASSETS.attackUp.effect,
  "MAGIC/17": STAGE1_ACTION_PRESENTATION_ASSETS.poison.rise,
  "MAGIC/18": STAGE1_ACTION_PRESENTATION_ASSETS.poison.cloud,
  "MAGIC/44": STAGE1_ACTION_PRESENTATION_ASSETS.confusion.effect,
  "MAGIC/46": STAGE1_ACTION_PRESENTATION_ASSETS.attackDown.effect,
  "MAGIC/45": STAGE1_ACTION_PRESENTATION_ASSETS.defenseDown.effect,
  "MAGIC/36": STAGE1_ACTION_PRESENTATION_ASSETS.spellSeal.effect,
  "MAGIC/33": STAGE1_ACTION_PRESENTATION_ASSETS.defenseUp.effect,
  "UN/57": STAGE1_ACTION_PRESENTATION_ASSETS.dispel.effect,
  "MAGIC/50": STAGE1_ACTION_PRESENTATION_ASSETS.stomp1.side1,
  "MAGIC/49": STAGE1_ACTION_PRESENTATION_ASSETS.stomp1.side2,
  "MAGIC/52": STAGE1_ACTION_PRESENTATION_ASSETS.stomp2.side1,
  "MAGIC/51": STAGE1_ACTION_PRESENTATION_ASSETS.stomp2.side2,
  "MAGIC/54": STAGE1_ACTION_PRESENTATION_ASSETS.stomp3.side1,
  "MAGIC/53": STAGE1_ACTION_PRESENTATION_ASSETS.stomp3.side2,
  "MAGIC/19": STAGE1_ACTION_PRESENTATION_ASSETS.wd.effect,
} as const satisfies Readonly<Record<string, readonly string[]>>;

export const TECHNIQUE_LAB_FORMAL_AUDIO_ASSETS = {
  "E/43": STAGE1_ACTION_AUDIO_ASSETS["e-43"],
  "E/63": STAGE1_ACTION_AUDIO_ASSETS["e-63"],
  "E/41": STAGE1_ACTION_AUDIO_ASSETS["e-41"],
  "E/9": STAGE1_ACTION_AUDIO_ASSETS["e-9"],
  "MAGIC/83": STAGE0_ACTION_AUDIO_ASSETS["magic-83"],
  "E/51": STAGE1_ACTION_AUDIO_ASSETS["e-51"],
  "E/36": STAGE1_ACTION_AUDIO_ASSETS["e-36"],
  "UN/51": STAGE1_ACTION_AUDIO_ASSETS["un-51"],
  "E/58": STAGE1_ACTION_AUDIO_ASSETS["e-58"],
  "E/8": STAGE1_ACTION_AUDIO_ASSETS["e-8"],
  "UN/52": STAGE1_ACTION_AUDIO_ASSETS["un-52"],
  "UN/50": STAGE1_ACTION_AUDIO_ASSETS["un-50"],
  "MAGIC/82": STAGE1_ACTION_AUDIO_ASSETS["magic-82"],
} as const satisfies Readonly<Record<string, string>>;
