[sdl]
fullscreen = false
autolock = false
waitonerror = false
showmenu = false

[log]
logfile = /Users/ziyu/Workspace/GameDev/WebTest/TS2/reverse/logs/dosbox-x-ui.log
files = false
exec = false
dosmisc = false
int21 = false
fileio = false

[dosbox]
machine = svga_s3
captures = /Users/ziyu/Workspace/GameDev/WebTest/TS2/reverse/captures
memsize = 16

[cpu]
core = normal
cycles = fixed 12000

[mixer]
nosound = true

[midi]
mpu401 = none

[sblaster]
sbtype = none

[speaker]
pcspeaker = false

[dos]
xms = true
ems = true
umb = true

[autoexec]
mount c "/Users/ziyu/Workspace/GameDev/WebTest/TS2/reverse/work/ANGEL2"
c:
GO.EXE
exit
