[sdl]
fullscreen = false
autolock = false
waitonerror = false
showmenu = false

[log]
logfile = reverse/logs/dosbox-x-trace.log
files = debug
exec = true
dosmisc = false
int21 = false
fileio = true
debuggerrun = debugger

[dosbox]
machine = svga_s3
captures = reverse/captures
memsize = 16

[cpu]
core = normal
cycles = fixed 12000

[mixer]
nosound = true

[midi]
mpu401 = none

[sblaster]
sbtype = none

[speaker]
pcspeaker = false

[dos]
xms = true
ems = true
umb = true

[autoexec]
mount c "reverse/work/ANGEL2"
c:
GO.EXE
exit
